// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

import {InkGenes} from "../src/lib/InkGenes.sol";
import {FixedPoint} from "../src/lib/FixedPoint.sol";
import {Denominations} from "../src/lib/Denominations.sol";

/// @notice The pure Ink Genes library: constant-table parity against the canonical TypeScript
///         (`preview/src/canonical/ink.ts`), frozen mint vectors, the compose walk's
///         order-invariance and survivor-choice sensitivity, and the center worked example.
/// @dev Fixtures are generated by `preview/scripts/genFixtures.ts`, same file and same
///      regeneration command (`npm run fixtures` in `preview/`) as the renderer parity suite.
///      Named `...ParityTest` so `forge test --mc Parity` picks it up alongside
///      `test/Parity.t.sol`.
contract InkGenesParityTest is Test {
    string internal json;

    function setUp() public {
        json = vm.readFile(string.concat("test/fixtures/fixtures.", Denominations.LADDER_NAME, ".json"));
    }

    /* ------------------------------------------------------------------ *
     *  Test 1: constant tables
     * ------------------------------------------------------------------ */

    /// @notice `GENE_PROBABILITY` and `GENE_NAMES` must equal the TypeScript tables byte for
    ///         byte, the same way `Denominations` is kept in lockstep with `denominations.ts`.
    function test_ConstantTablesMatchTypeScript() public view {
        assertEq(uint8(InkGenes.GENE_COUNT), vm.parseUint(vm.parseJsonString(json, ".geneCount")));

        string[] memory expectedNames = vm.parseJsonStringArray(json, ".geneNames");
        string[] memory expectedProbability = vm.parseJsonStringArray(json, ".geneProbability");
        assertEq(expectedNames.length, uint8(InkGenes.GENE_COUNT));
        assertEq(expectedProbability.length, uint8(InkGenes.GENE_COUNT));

        for (uint256 gene = 0; gene < uint8(InkGenes.GENE_COUNT); ++gene) {
            assertEq(InkGenes.geneNameAt(gene), expectedNames[gene], "gene name drifted from TS");
            assertEq(
                FixedPoint.fmt(InkGenes.geneProbabilityAt(gene)),
                expectedProbability[gene],
                "gene probability drifted from TS"
            );
        }
    }

    /* ------------------------------------------------------------------ *
     *  Test 2: mint gene vectors
     * ------------------------------------------------------------------ */

    /// @notice Fixed vector seeds -> expected gene, generated by the TS implementation. Covers
    ///         every gene for dust (denomIndex 0) and every reachable gene for a non-dust tier
    ///         ({Sparse, Murk, Dense} only).
    function test_MintVectorsMatchTypeScript() public view {
        string[] memory seedStr = vm.parseJsonStringArray(json, ".inkMintSeed");
        string[] memory denomStr = vm.parseJsonStringArray(json, ".inkMintDenomIndex");
        string[] memory geneStr = vm.parseJsonStringArray(json, ".inkMintGene");
        uint256 n = seedStr.length;
        assertEq(n, 10, "expected 7 dust + 3 non-dust vectors");

        for (uint256 i = 0; i < n; ++i) {
            bytes32 seed = vm.parseBytes32(seedStr[i]);
            uint8 denomIndex = uint8(vm.parseUint(denomStr[i]));
            uint8 expected = uint8(vm.parseUint(geneStr[i]));
            assertEq(InkGenes.geneAtMint(seed, denomIndex), expected, "mint gene drifted from TS");
        }
    }

    /// @notice Non-dust mints never yield genes outside {Sparse, Murk, Dense}.
    function testFuzz_NonDustMintsStayInTheNarrowBand(bytes32 seed, uint8 denomIndex) public pure {
        denomIndex = uint8(bound(denomIndex, 1, 8));
        uint8 gene = InkGenes.geneAtMint(seed, denomIndex);
        assertTrue(
            gene == InkGenes.SPARSE || gene == InkGenes.MURK || gene == InkGenes.DENSE,
            "non-dust mint escaped the narrow band"
        );
    }

    /// @notice Dust mints (denomIndex 0) may reach any of the seven genes; the narrow-band
    ///         restriction is specific to denomIndex != 0.
    function testFuzz_DustMintsStayInRange(bytes32 seed) public pure {
        uint8 gene = InkGenes.geneAtMint(seed, 0);
        assertLt(gene, uint8(InkGenes.GENE_COUNT));
    }

    /* ------------------------------------------------------------------ *
     *  Test 4: the center worked example (impl spec §2.3)
     * ------------------------------------------------------------------ */

    /// @notice survivor Solid(6) dust (1 unit) + four burns Murk(3) dust (1 unit each):
    ///         sumW = 6 + 4*3 = 18, units = 5, center = (36 + 5) / 10 = 4 (Dense). The true mean
    ///         3.6 rounds up, per the pinned half-up rule.
    function test_CenterWorkedExample() public pure {
        uint256 sumW = uint256(InkGenes.SOLID) * 1 + uint256(InkGenes.MURK) * 4;
        uint256 units = 5;
        assertEq(sumW, 18);
        assertEq(InkGenes.center(sumW, units), InkGenes.DENSE, "worked example diverged");
    }

    /// @notice The general half-up rounding rule, fuzzed against a same-gene pool (where the
    ///         mean is exact and rounding cannot matter) and against the boundary directly.
    function testFuzz_CenterRoundsHalfUp(uint8 gene, uint8 units) public pure {
        gene = gene % uint8(InkGenes.GENE_COUNT);
        units = uint8(bound(units, 1, 200));
        // A uniform pool's mean is exact, so center must equal the shared gene regardless of
        // how many units back it.
        assertEq(InkGenes.center(uint256(gene) * units, units), gene);
    }

    /// @notice A poised half-integer mean (exactly x.5) always rounds up, the general form of
    ///         the worked example above.
    function testFuzz_ExactHalfRoundsUp(uint8 low, uint8 weight) public pure {
        low = low % (uint8(InkGenes.GENE_COUNT) - 1); // 0..5
        uint8 high = low + 1; // the adjacent gene
        weight = uint8(bound(weight, 1, 100));

        // `weight` units of `low`, `weight` units of `high`: mean is exactly low + 0.5,
        // whatever the common weight is.
        uint256 sumW = (uint256(low) + uint256(high)) * weight;
        uint256 units = uint256(weight) * 2;
        assertEq(InkGenes.center(sumW, units), high, "x.5 did not round up to the higher gene");
    }

    /* ------------------------------------------------------------------ *
     *  Test 5: compose order-invariance
     * ------------------------------------------------------------------ */

    /// @notice `burnSeedFold` is an XOR fold, so calldata order cannot affect
    ///         `geneAtCompose`'s output: at least three permutations of the same four burn
    ///         seeds must fold to the identical value, and therefore produce the identical gene.
    function testFuzz_ComposeIsOrderInvariant(
        bytes32 survivorSeed,
        bytes32 a,
        bytes32 b,
        bytes32 c,
        bytes32 d,
        uint8 survivorGene,
        uint8 oldIndex,
        uint8 span,
        uint8 best,
        uint8 worst,
        uint8 centerGene
    ) public pure {
        survivorGene = survivorGene % uint8(InkGenes.GENE_COUNT);
        best = best % uint8(InkGenes.GENE_COUNT);
        worst = worst % uint8(InkGenes.GENE_COUNT);
        centerGene = centerGene % uint8(InkGenes.GENE_COUNT);
        oldIndex = oldIndex % 8; // leave room for at least one tier above
        uint8 newIndex = oldIndex + 1 + (span % (8 - oldIndex));

        uint256 foldForward = uint256(a) ^ uint256(b) ^ uint256(c) ^ uint256(d);
        uint256 foldReversed = uint256(d) ^ uint256(c) ^ uint256(b) ^ uint256(a);
        uint256 foldShuffled = uint256(b) ^ uint256(d) ^ uint256(a) ^ uint256(c);
        assertEq(foldForward, foldReversed, "XOR fold is not order-invariant");
        assertEq(foldForward, foldShuffled, "XOR fold is not order-invariant");

        uint8 g1 = InkGenes.geneAtCompose(
            survivorSeed, foldForward, survivorGene, oldIndex, newIndex, best, worst, centerGene
        );
        uint8 g2 = InkGenes.geneAtCompose(
            survivorSeed, foldReversed, survivorGene, oldIndex, newIndex, best, worst, centerGene
        );
        uint8 g3 = InkGenes.geneAtCompose(
            survivorSeed, foldShuffled, survivorGene, oldIndex, newIndex, best, worst, centerGene
        );
        assertEq(g1, g2, "reordering burnIds changed the gene");
        assertEq(g1, g3, "reordering burnIds changed the gene");
    }

    /// @notice A homogeneous pool (best == worst == center == survivorGene) is a fixed point of
    ///         the walk: every tier's target equals the survivor's own gene, so no step ever
    ///         moves it, for any tier count.
    function testFuzz_HomogeneousPoolIsAFixedPoint(
        bytes32 survivorSeed,
        uint256 burnSeedFold,
        uint8 gene,
        uint8 oldIndex,
        uint8 span
    ) public pure {
        gene = gene % uint8(InkGenes.GENE_COUNT);
        oldIndex = oldIndex % 8;
        uint8 newIndex = oldIndex + 1 + (span % (8 - oldIndex));

        uint8 result =
            InkGenes.geneAtCompose(survivorSeed, burnSeedFold, gene, oldIndex, newIndex, gene, gene, gene);
        assertEq(result, gene, "a uniform pool's gene drifted");
    }

    /* ------------------------------------------------------------------ *
     *  Test 6: survivor choice matters
     * ------------------------------------------------------------------ */

    /// @notice A concrete five-dust-into-0.05 candidate set (found by search in
    ///         `genFixtures.ts`) where composing with one member as survivor yields a different
    ///         gene than composing the identical multiset with another member as survivor.
    ///         `best`, `worst` and `center` are pool statistics over the whole multiset, so they
    ///         are identical either way; re-derived here from just the five seeds, so this is
    ///         not trusting a TS-computed intermediate value, only the two final outcomes.
    function test_SurvivorChoiceChangesTheGene() public view {
        string[] memory seedStr = vm.parseJsonStringArray(json, ".inkSurvivorSeeds");
        string[] memory geneStr = vm.parseJsonStringArray(json, ".inkSurvivorGenes");
        assertEq(seedStr.length, 5);

        bytes32[5] memory seeds;
        uint8[5] memory genes;
        uint256 sumW;
        uint8 best;
        uint8 worst = InkGenes.SOLID;
        for (uint256 i = 0; i < 5; ++i) {
            seeds[i] = vm.parseBytes32(seedStr[i]);
            uint8 gene = InkGenes.geneAtMint(seeds[i], 0);
            assertEq(gene, uint8(vm.parseUint(geneStr[i])), "fixture gene drifted from TS");
            genes[i] = gene;
            sumW += gene;
            if (gene > best) best = gene;
            if (gene < worst) worst = gene;
        }
        uint8 centerGene = InkGenes.center(sumW, 5);

        uint256 indexA = vm.parseUint(vm.parseJsonString(json, ".inkSurvivorIndexA"));
        uint256 indexB = vm.parseUint(vm.parseJsonString(json, ".inkSurvivorIndexB"));
        uint8 expectedA = uint8(vm.parseUint(vm.parseJsonString(json, ".inkSurvivorGeneA")));
        uint8 expectedB = uint8(vm.parseUint(vm.parseJsonString(json, ".inkSurvivorGeneB")));

        uint256 foldA;
        uint256 foldB;
        for (uint256 i = 0; i < 5; ++i) {
            if (i != indexA) foldA ^= uint256(seeds[i]);
            if (i != indexB) foldB ^= uint256(seeds[i]);
        }

        uint8 geneA =
            InkGenes.geneAtCompose(seeds[indexA], foldA, genes[indexA], 0, 1, best, worst, centerGene);
        uint8 geneB =
            InkGenes.geneAtCompose(seeds[indexB], foldB, genes[indexB], 0, 1, best, worst, centerGene);

        assertEq(geneA, expectedA, "survivor A outcome drifted from TS");
        assertEq(geneB, expectedB, "survivor B outcome drifted from TS");
        assertTrue(geneA != geneB, "the fixture no longer demonstrates survivor choice mattering");
    }

    /// @notice Multi-tier compose walk pinned to the TS canonical: vectors spanning every tier
    ///         span T = 1..8 with heterogeneous pool statistics. Closes the gap where only the
    ///         T = 1 survivor case cross-checked `geneAtCompose` against TypeScript.
    // Column arrays for the compose-walk fixture. Bundled into a struct rather than nine
    // locals so the enclosing function stays off the stack-too-deep limit under the
    // non-optimized codegen `forge coverage` uses.
    struct ComposeWalkVectors {
        string[] seed;
        string[] fold;
        string[] sg;
        string[] oldI;
        string[] newI;
        string[] bst;
        string[] wst;
        string[] ctr;
        string[] exp;
    }

    function test_ComposeWalkVectorsMatchTypeScript() public view {
        ComposeWalkVectors memory v = ComposeWalkVectors({
            seed: vm.parseJsonStringArray(json, ".inkWalkSurvivorSeed"),
            fold: vm.parseJsonStringArray(json, ".inkWalkBurnFold"),
            sg: vm.parseJsonStringArray(json, ".inkWalkSurvivorGene"),
            oldI: vm.parseJsonStringArray(json, ".inkWalkOldIndex"),
            newI: vm.parseJsonStringArray(json, ".inkWalkNewIndex"),
            bst: vm.parseJsonStringArray(json, ".inkWalkBest"),
            wst: vm.parseJsonStringArray(json, ".inkWalkWorst"),
            ctr: vm.parseJsonStringArray(json, ".inkWalkCenter"),
            exp: vm.parseJsonStringArray(json, ".inkWalkExpectedGene")
        });

        uint256 n = v.seed.length;
        assertEq(n, 40, "expected 40 compose-walk vectors");
        for (uint256 i = 0; i < n; ++i) {
            uint8 got = InkGenes.geneAtCompose(
                vm.parseBytes32(v.seed[i]),
                vm.parseUint(v.fold[i]),
                uint8(vm.parseUint(v.sg[i])),
                uint8(vm.parseUint(v.oldI[i])),
                uint8(vm.parseUint(v.newI[i])),
                uint8(vm.parseUint(v.bst[i])),
                uint8(vm.parseUint(v.wst[i])),
                uint8(vm.parseUint(v.ctr[i]))
            );
            assertEq(got, uint8(vm.parseUint(v.exp[i])), "compose walk drifted from TS");
        }
    }
}
