// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

import {ShapeRenderer} from "../src/ShapeRenderer.sol";
import {FixedPoint} from "../src/lib/FixedPoint.sol";

/// @notice Byte-for-byte parity between the Solidity renderer and the canonical TypeScript
///         renderer.
/// @dev The fixtures are generated by `preview/scripts/genFixtures.ts`. "Visually similar" is
///      not the bar here: the strings must be identical, including every decimal digit,
///      attribute order and space. Regenerate with `npm run fixtures` in preview/.
contract ParityTest is Test {
    ShapeRenderer internal renderer;

    string internal json;
    string[] internal why;
    string[] internal expectedSvg;
    string[] internal expectedMetadata;
    string[] internal expectedModules;
    string[] internal expectedCell;
    string[] internal expectedFill;
    string[] internal expectedTarget;
    string[] internal expectedWRatio;
    string[] internal colsStr;
    string[] internal rowsStr;
    bytes32[] internal seeds;
    uint256[] internal amounts;
    uint256[] internal tokenIds;
    uint256[] internal originCounts;
    bool[] internal inverteds;
    uint8[] internal genes;
    uint256 internal count;

    function setUp() public {
        renderer = new ShapeRenderer();
        json = vm.readFile("test/fixtures/fixtures.json");

        why = vm.parseJsonStringArray(json, ".why");
        expectedSvg = vm.parseJsonStringArray(json, ".svg");
        expectedMetadata = vm.parseJsonStringArray(json, ".metadata");
        expectedModules = vm.parseJsonStringArray(json, ".modules");
        expectedCell = vm.parseJsonStringArray(json, ".cell");
        expectedFill = vm.parseJsonStringArray(json, ".fill");
        expectedTarget = vm.parseJsonStringArray(json, ".target");
        expectedWRatio = vm.parseJsonStringArray(json, ".wRatio");
        colsStr = vm.parseJsonStringArray(json, ".cols");
        rowsStr = vm.parseJsonStringArray(json, ".rows");

        string[] memory seedStr = vm.parseJsonStringArray(json, ".seed");
        string[] memory amountStr = vm.parseJsonStringArray(json, ".amountWei");
        string[] memory tokenIdStr = vm.parseJsonStringArray(json, ".tokenId");
        string[] memory originStr = vm.parseJsonStringArray(json, ".originCount");
        string[] memory invertedStr = vm.parseJsonStringArray(json, ".inverted");
        string[] memory geneStr = vm.parseJsonStringArray(json, ".inkGene");

        count = seedStr.length;
        assertGt(count, 60, "fixture corpus unexpectedly small");

        for (uint256 i = 0; i < count; ++i) {
            seeds.push(vm.parseBytes32(seedStr[i]));
            amounts.push(vm.parseUint(amountStr[i]));
            tokenIds.push(vm.parseUint(tokenIdStr[i]));
            originCounts.push(vm.parseUint(originStr[i]));
            inverteds.push(_isTrue(invertedStr[i]));
            genes.push(uint8(vm.parseUint(geneStr[i])));
        }
    }

    function _isTrue(string memory s) private pure returns (bool) {
        return keccak256(bytes(s)) == keccak256(bytes("true"));
    }

    /// @notice The split child-seed derivation the frontend previews with must equal the
    ///         on-chain rule byte for byte. The fixtures carry TS-computed child seeds; here the
    ///         Solidity derivation is recomputed and compared. Proves the (bytes32, uint256)
    ///         packing agrees across the two implementations.
    function test_ChildSeedDerivationMatchesTypeScript() public view {
        string[] memory parents = vm.parseJsonStringArray(json, ".childParent");
        string[] memory indices = vm.parseJsonStringArray(json, ".childIndex");
        string[] memory children = vm.parseJsonStringArray(json, ".childSeed");
        uint256 n = parents.length;
        assertGt(n, 0, "no child-seed fixtures");
        for (uint256 i = 0; i < n; ++i) {
            bytes32 parent = vm.parseBytes32(parents[i]);
            uint256 index = vm.parseUint(indices[i]);
            bytes32 got = keccak256(abi.encodePacked(parent, index));
            assertEq(got, vm.parseBytes32(children[i]), "child seed derivation drifted from TS");
        }
    }

    /// @dev A Shape carries no type, so its artwork does not depend on the token id at all.
    ///      Two tokens with the same seed and denomination render identically by design.
    function test_ArtworkIsIndependentOfTokenId() public view {
        for (uint256 i = 0; i < 8; ++i) {
            assertEq(
                renderer.renderSVG(seeds[i], amounts[i], false, genes[i]),
                renderer.renderSVG(seeds[i], amounts[i], false, genes[i]),
                "renderSVG is not a pure function of seed and denomination"
            );
        }
    }

    /// @notice Every fixture's SVG must match byte for byte.
    function test_SvgIsByteIdenticalToTypeScript() public view {
        for (uint256 i = 0; i < count; ++i) {
            string memory got = renderer.renderSVG(seeds[i], amounts[i], inverteds[i], genes[i]);
            assertEq(got, expectedSvg[i], why[i]);
        }
    }

    /// @notice Metadata JSON, including the inlined base64 image, must match byte for byte.
    function test_MetadataIsByteIdenticalToTypeScript() public view {
        for (uint256 i = 0; i < count; ++i) {
            string memory got = renderer.metadataJSON(
                seeds[i], amounts[i], tokenIds[i], originCounts[i], inverteds[i], genes[i]
            );
            assertEq(got, expectedMetadata[i], why[i]);
        }
    }

    /// @notice The glyph trait must come from the same stream as the artwork.
    function test_ModuleSequenceMatches() public view {
        for (uint256 i = 0; i < count; ++i) {
            assertEq(
                renderer.moduleSequence(seeds[i], amounts[i], genes[i]), expectedModules[i], why[i]
            );
        }
    }

    /// @notice Card-level parameters must agree, not just the rendered result. This localises
    ///         a failure to the composition rather than the string assembly.
    function test_CardParametersMatch() public view {
        for (uint256 i = 0; i < count; ++i) {
            ShapeRenderer.Card memory c = renderer.compose(seeds[i], amounts[i], genes[i]);
            assertEq(FixedPoint.toString(c.cols), colsStr[i], "cols");
            assertEq(FixedPoint.toString(c.rows), rowsStr[i], "rows");
            assertEq(FixedPoint.fmt(c.cell), expectedCell[i], "cell");
            assertEq(FixedPoint.fmt(c.fill), expectedFill[i], "fill");
            assertEq(FixedPoint.fmt(c.target), expectedTarget[i], "target");
            assertEq(FixedPoint.fmt(c.wRatio), expectedWRatio[i], "wRatio");
        }
    }

    /// @notice Rendering is a pure function of its inputs and of nothing else.
    function test_RenderIsStableAcrossChainState() public {
        bytes32 seed = seeds[0];
        uint256 amount = amounts[0];
        uint8 gene = genes[0];
        string memory first = renderer.renderSVG(seed, amount, false, gene);

        vm.roll(block.number + 5_000);
        vm.warp(block.timestamp + 400 days);
        vm.prevrandao(bytes32(uint256(0xdeadbeef)));
        vm.fee(999 gwei);
        vm.chainId(1234);

        assertEq(
            renderer.renderSVG(seed, amount, false, gene), first, "renderer read mutable state"
        );
    }

    /// @notice A second deployment of the same bytecode renders identically. There is no
    ///         per-instance state that could make artwork instance-dependent.
    function test_SecondRendererInstanceAgrees() public {
        ShapeRenderer other = new ShapeRenderer();
        for (uint256 i = 0; i < 12; ++i) {
            assertEq(
                other.renderSVG(seeds[i], amounts[i], inverteds[i], genes[i]),
                renderer.renderSVG(seeds[i], amounts[i], inverteds[i], genes[i])
            );
        }
    }
}
