// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";

import {ShapeRenderer} from "../src/ShapeRenderer.sol";
import {FixedPoint} from "../src/lib/FixedPoint.sol";
import {Denominations} from "../src/lib/Denominations.sol";
import {GeometrySampling} from "../src/lib/GeometrySampling.sol";

/// @notice Byte-for-byte parity between the Solidity renderer and the canonical TypeScript
///         renderer.
/// @dev The fixtures are generated by `preview/scripts/genFixtures.ts`. "Visually similar" is
///      not the bar here: the strings must be identical, including every decimal digit,
///      attribute order and space. Regenerate with `npm run fixtures` in preview/.
contract ParityTest is Test {
    /// @dev The canonical default copy the fixtures were generated with (see render.ts).
    string internal constant NAME_PREFIX = "Shape ";
    string internal constant DESCRIPTION = "Shapes are ETH-backed onchain objects. Each Shape wraps an exact amount of ETH. "
        "Burning it returns exactly that amount to its owner. Higher denominations resolve "
        "into fewer, larger modules. Artwork and metadata are generated entirely onchain.";

    ShapeRenderer internal renderer;

    string internal json;
    string[] internal why;
    string[] internal expectedSvg;
    string[] internal expectedMetadata;
    string[] internal expectedModules;
    string[] internal expectedCell;
    string[] internal expectedFill;
    string[] internal expectedTarget;
    string[] internal expectedWRatio;
    string[] internal colsStr;
    string[] internal rowsStr;
    bytes32[] internal seeds;
    uint256[] internal amounts;
    uint256[] internal tokenIds;
    uint256[] internal originCounts;
    bool[] internal inverteds;
    uint8[] internal genes;
    uint256[] internal composeDepths;
    uint256 internal count;

    /// @dev Every compose-sampling fixture case carries exactly this many burns, flattened
    ///      row-major into the parallel `sampleComposeBurn*` arrays below. Must match
    ///      `BURNS_PER_COMPOSE_CASE` in preview/scripts/genFixtures.ts.
    uint256 internal constant BURNS_PER_COMPOSE_CASE = 3;

    // --- materialized module sampling (SAMPLING_SPEC.md): compose ---
    string[] internal sampleComposeWhy;
    bytes32[] internal sampleComposeSurvivorSeed;
    uint8[] internal sampleComposeSurvivorDenomIndex;
    uint8[] internal sampleComposeSurvivorInkGene;
    bytes[] internal sampleComposeSurvivorModules;
    uint8[] internal sampleComposeNewIndex;
    bytes[] internal sampleComposeExpected;
    uint256[] internal sampleComposeBurnTokenId;
    bytes32[] internal sampleComposeBurnSeed;
    uint8[] internal sampleComposeBurnDenomIndex;
    uint8[] internal sampleComposeBurnInkGene;
    bytes[] internal sampleComposeBurnModules;

    // --- materialized module sampling: split ---
    string[] internal sampleSplitWhy;
    bytes32[] internal sampleSplitParentSeed;
    uint8[] internal sampleSplitParentDenomIndex;
    uint8[] internal sampleSplitParentInkGene;
    bytes[] internal sampleSplitParentModules;
    uint8[] internal sampleSplitChildDenomIndex;
    uint256[] internal sampleSplitChildIndex;
    bytes[] internal sampleSplitExpected;

    // --- sampled render surfaces (grammar v2) ---
    string[] internal sampledRenderWhy;
    uint8[] internal sampledRenderDenomIndex;
    uint256[] internal sampledRenderAmountWei;
    bytes[] internal sampledRenderModules;
    uint8[] internal sampledRenderInkGene;
    uint256[] internal sampledRenderTokenId;
    uint256[] internal sampledRenderOriginCount;
    bool[] internal sampledRenderInverted;
    uint256[] internal sampledRenderComposeDepth;
    string[] internal sampledRenderSvg;
    string[] internal sampledRenderMetadata;
    string[] internal sampledRenderModuleSequence;

    function setUp() public {
        renderer = new ShapeRenderer();
        json = vm.readFile("test/fixtures/fixtures.json");

        why = vm.parseJsonStringArray(json, ".why");
        expectedSvg = vm.parseJsonStringArray(json, ".svg");
        expectedMetadata = vm.parseJsonStringArray(json, ".metadata");
        expectedModules = vm.parseJsonStringArray(json, ".modules");
        expectedCell = vm.parseJsonStringArray(json, ".cell");
        expectedFill = vm.parseJsonStringArray(json, ".fill");
        expectedTarget = vm.parseJsonStringArray(json, ".target");
        expectedWRatio = vm.parseJsonStringArray(json, ".wRatio");
        colsStr = vm.parseJsonStringArray(json, ".cols");
        rowsStr = vm.parseJsonStringArray(json, ".rows");

        string[] memory seedStr = vm.parseJsonStringArray(json, ".seed");
        string[] memory amountStr = vm.parseJsonStringArray(json, ".amountWei");
        string[] memory tokenIdStr = vm.parseJsonStringArray(json, ".tokenId");
        string[] memory originStr = vm.parseJsonStringArray(json, ".originCount");
        string[] memory invertedStr = vm.parseJsonStringArray(json, ".inverted");
        string[] memory geneStr = vm.parseJsonStringArray(json, ".inkGene");
        string[] memory composeDepthStr = vm.parseJsonStringArray(json, ".composeDepth");

        count = seedStr.length;
        assertGt(count, 60, "fixture corpus unexpectedly small");

        for (uint256 i = 0; i < count; ++i) {
            seeds.push(vm.parseBytes32(seedStr[i]));
            amounts.push(vm.parseUint(amountStr[i]));
            tokenIds.push(vm.parseUint(tokenIdStr[i]));
            originCounts.push(vm.parseUint(originStr[i]));
            inverteds.push(_isTrue(invertedStr[i]));
            genes.push(uint8(vm.parseUint(geneStr[i])));
            composeDepths.push(vm.parseUint(composeDepthStr[i]));
        }

        _loadSamplingFixtures();
    }

    /// @dev Parses the SAMPLING_SPEC.md fixture columns generated by genFixtures.ts: the
    ///      compose- and split-sampling procedure vectors, and the sampled render surface cases.
    ///      Split out of `setUp` to keep it under the stack/local-variable limit.
    function _loadSamplingFixtures() private {
        sampleComposeWhy = vm.parseJsonStringArray(json, ".sampleComposeWhy");
        {
            string[] memory s = vm.parseJsonStringArray(json, ".sampleComposeSurvivorSeed");
            string[] memory di = vm.parseJsonStringArray(json, ".sampleComposeSurvivorDenomIndex");
            string[] memory ig = vm.parseJsonStringArray(json, ".sampleComposeSurvivorInkGene");
            string[] memory mo = vm.parseJsonStringArray(json, ".sampleComposeSurvivorModules");
            string[] memory ni = vm.parseJsonStringArray(json, ".sampleComposeNewIndex");
            string[] memory ex = vm.parseJsonStringArray(json, ".sampleComposeExpected");
            uint256 nCases = s.length;
            for (uint256 i = 0; i < nCases; ++i) {
                sampleComposeSurvivorSeed.push(vm.parseBytes32(s[i]));
                sampleComposeSurvivorDenomIndex.push(uint8(vm.parseUint(di[i])));
                sampleComposeSurvivorInkGene.push(uint8(vm.parseUint(ig[i])));
                sampleComposeSurvivorModules.push(vm.parseBytes(mo[i]));
                sampleComposeNewIndex.push(uint8(vm.parseUint(ni[i])));
                sampleComposeExpected.push(vm.parseBytes(ex[i]));
            }
        }
        {
            string[] memory tid = vm.parseJsonStringArray(json, ".sampleComposeBurnTokenId");
            string[] memory s = vm.parseJsonStringArray(json, ".sampleComposeBurnSeed");
            string[] memory di = vm.parseJsonStringArray(json, ".sampleComposeBurnDenomIndex");
            string[] memory ig = vm.parseJsonStringArray(json, ".sampleComposeBurnInkGene");
            string[] memory mo = vm.parseJsonStringArray(json, ".sampleComposeBurnModules");
            uint256 nBurns = tid.length;
            assertEq(
                nBurns,
                sampleComposeWhy.length * BURNS_PER_COMPOSE_CASE,
                "burn row count != cases * BURNS_PER_COMPOSE_CASE"
            );
            for (uint256 i = 0; i < nBurns; ++i) {
                sampleComposeBurnTokenId.push(vm.parseUint(tid[i]));
                sampleComposeBurnSeed.push(vm.parseBytes32(s[i]));
                sampleComposeBurnDenomIndex.push(uint8(vm.parseUint(di[i])));
                sampleComposeBurnInkGene.push(uint8(vm.parseUint(ig[i])));
                sampleComposeBurnModules.push(vm.parseBytes(mo[i]));
            }
        }

        sampleSplitWhy = vm.parseJsonStringArray(json, ".sampleSplitWhy");
        {
            string[] memory s = vm.parseJsonStringArray(json, ".sampleSplitParentSeed");
            string[] memory di = vm.parseJsonStringArray(json, ".sampleSplitParentDenomIndex");
            string[] memory ig = vm.parseJsonStringArray(json, ".sampleSplitParentInkGene");
            string[] memory mo = vm.parseJsonStringArray(json, ".sampleSplitParentModules");
            string[] memory cd = vm.parseJsonStringArray(json, ".sampleSplitChildDenomIndex");
            string[] memory ci = vm.parseJsonStringArray(json, ".sampleSplitChildIndex");
            string[] memory ex = vm.parseJsonStringArray(json, ".sampleSplitExpected");
            uint256 n = s.length;
            for (uint256 i = 0; i < n; ++i) {
                sampleSplitParentSeed.push(vm.parseBytes32(s[i]));
                sampleSplitParentDenomIndex.push(uint8(vm.parseUint(di[i])));
                sampleSplitParentInkGene.push(uint8(vm.parseUint(ig[i])));
                sampleSplitParentModules.push(vm.parseBytes(mo[i]));
                sampleSplitChildDenomIndex.push(uint8(vm.parseUint(cd[i])));
                sampleSplitChildIndex.push(vm.parseUint(ci[i]));
                sampleSplitExpected.push(vm.parseBytes(ex[i]));
            }
        }

        sampledRenderWhy = vm.parseJsonStringArray(json, ".sampledRenderWhy");
        sampledRenderSvg = vm.parseJsonStringArray(json, ".sampledRenderSvg");
        sampledRenderMetadata = vm.parseJsonStringArray(json, ".sampledRenderMetadata");
        sampledRenderModuleSequence = vm.parseJsonStringArray(json, ".sampledRenderModuleSequence");
        {
            string[] memory di = vm.parseJsonStringArray(json, ".sampledRenderDenomIndex");
            string[] memory aw = vm.parseJsonStringArray(json, ".sampledRenderAmountWei");
            string[] memory mo = vm.parseJsonStringArray(json, ".sampledRenderModules");
            string[] memory ig = vm.parseJsonStringArray(json, ".sampledRenderInkGene");
            string[] memory tid = vm.parseJsonStringArray(json, ".sampledRenderTokenId");
            string[] memory oc = vm.parseJsonStringArray(json, ".sampledRenderOriginCount");
            string[] memory inv = vm.parseJsonStringArray(json, ".sampledRenderInverted");
            string[] memory cdep = vm.parseJsonStringArray(json, ".sampledRenderComposeDepth");
            uint256 n = di.length;
            for (uint256 i = 0; i < n; ++i) {
                sampledRenderDenomIndex.push(uint8(vm.parseUint(di[i])));
                sampledRenderAmountWei.push(vm.parseUint(aw[i]));
                sampledRenderModules.push(vm.parseBytes(mo[i]));
                sampledRenderInkGene.push(uint8(vm.parseUint(ig[i])));
                sampledRenderTokenId.push(vm.parseUint(tid[i]));
                sampledRenderOriginCount.push(vm.parseUint(oc[i]));
                sampledRenderInverted.push(_isTrue(inv[i]));
                sampledRenderComposeDepth.push(vm.parseUint(cdep[i]));
            }
        }
    }

    function _isTrue(string memory s) private pure returns (bool) {
        return keccak256(bytes(s)) == keccak256(bytes("true"));
    }

    /// @notice The split child-seed derivation the frontend previews with must equal the
    ///         on-chain rule byte for byte. The fixtures carry TS-computed child seeds; here the
    ///         Solidity derivation is recomputed and compared. Proves the (bytes32, uint256)
    ///         packing agrees across the two implementations.
    function test_ChildSeedDerivationMatchesTypeScript() public view {
        string[] memory parents = vm.parseJsonStringArray(json, ".childParent");
        string[] memory indices = vm.parseJsonStringArray(json, ".childIndex");
        string[] memory children = vm.parseJsonStringArray(json, ".childSeed");
        uint256 n = parents.length;
        assertGt(n, 0, "no child-seed fixtures");
        for (uint256 i = 0; i < n; ++i) {
            bytes32 parent = vm.parseBytes32(parents[i]);
            uint256 index = vm.parseUint(indices[i]);
            bytes32 got = keccak256(abi.encodePacked(parent, index));
            assertEq(got, vm.parseBytes32(children[i]), "child seed derivation drifted from TS");
        }
    }

    /// @dev A Shape carries no type, so its artwork does not depend on the token id at all.
    ///      Two tokens with the same seed and denomination render identically by design.
    function test_ArtworkIsIndependentOfTokenId() public view {
        for (uint256 i = 0; i < 8; ++i) {
            assertEq(
                renderer.renderSVG(seeds[i], amounts[i], false, genes[i]),
                renderer.renderSVG(seeds[i], amounts[i], false, genes[i]),
                "renderSVG is not a pure function of seed and denomination"
            );
        }
    }

    /// @notice Every fixture's SVG must match byte for byte.
    function test_SvgIsByteIdenticalToTypeScript() public view {
        for (uint256 i = 0; i < count; ++i) {
            string memory got = renderer.renderSVG(seeds[i], amounts[i], inverteds[i], genes[i]);
            assertEq(got, expectedSvg[i], why[i]);
        }
    }

    /// @notice Metadata JSON, including the inlined base64 image, must match byte for byte.
    function test_MetadataIsByteIdenticalToTypeScript() public view {
        for (uint256 i = 0; i < count; ++i) {
            string memory got = renderer.metadataJSON(
                seeds[i],
                amounts[i],
                tokenIds[i],
                originCounts[i],
                inverteds[i],
                genes[i],
                composeDepths[i],
                NAME_PREFIX,
                DESCRIPTION
            );
            assertEq(got, expectedMetadata[i], why[i]);
        }
    }

    /// @notice The glyph trait must come from the same stream as the artwork.
    function test_ModuleSequenceMatches() public view {
        for (uint256 i = 0; i < count; ++i) {
            assertEq(renderer.moduleSequence(seeds[i], amounts[i], genes[i]), expectedModules[i], why[i]);
        }
    }

    /// @notice Card-level parameters must agree, not just the rendered result. This localises
    ///         a failure to the composition rather than the string assembly.
    function test_CardParametersMatch() public view {
        for (uint256 i = 0; i < count; ++i) {
            ShapeRenderer.Card memory c = renderer.compose(seeds[i], amounts[i], genes[i]);
            assertEq(FixedPoint.toString(c.cols), colsStr[i], "cols");
            assertEq(FixedPoint.toString(c.rows), rowsStr[i], "rows");
            assertEq(FixedPoint.fmt(c.cell), expectedCell[i], "cell");
            assertEq(FixedPoint.fmt(c.fill), expectedFill[i], "fill");
            assertEq(FixedPoint.fmt(c.target), expectedTarget[i], "target");
            assertEq(FixedPoint.fmt(c.wRatio), expectedWRatio[i], "wRatio");
        }
    }

    /// @notice Rendering is a pure function of its inputs and of nothing else.
    function test_RenderIsStableAcrossChainState() public {
        bytes32 seed = seeds[0];
        uint256 amount = amounts[0];
        uint8 gene = genes[0];
        string memory first = renderer.renderSVG(seed, amount, false, gene);

        vm.roll(block.number + 5_000);
        vm.warp(block.timestamp + 400 days);
        vm.prevrandao(bytes32(uint256(0xdeadbeef)));
        vm.fee(999 gwei);
        vm.chainId(1234);

        assertEq(renderer.renderSVG(seed, amount, false, gene), first, "renderer read mutable state");
    }

    /// @notice A second deployment of the same bytecode renders identically. There is no
    ///         per-instance state that could make artwork instance-dependent.
    function test_SecondRendererInstanceAgrees() public {
        ShapeRenderer other = new ShapeRenderer();
        for (uint256 i = 0; i < 12; ++i) {
            assertEq(
                other.renderSVG(seeds[i], amounts[i], inverteds[i], genes[i]),
                renderer.renderSVG(seeds[i], amounts[i], inverteds[i], genes[i])
            );
        }
    }

    /* ------------------------------ materialized module sampling ------------------------------ */

    /// @notice `GeometrySampling.sampleCompose` against the TS canonical `sampleCompose`
    ///         (SAMPLING_SPEC.md section 5), over fixed donor sets: seed-derived donors only, a
    ///         mix of materialized and seed-derived donors, and — in one case — the burn
    ///         calldata order shuffled relative to ascending token id, so the Solidity sort must
    ///         independently reach the same canonical order the TS side sorts to.
    function test_ComposeSamplingMatchesTypeScript() public view {
        uint256 nCases = sampleComposeWhy.length;
        assertGt(nCases, 0, "no compose-sampling fixtures");
        for (uint256 i = 0; i < nCases; ++i) {
            GeometrySampling.Donor[] memory burnDonors = new GeometrySampling.Donor[](BURNS_PER_COMPOSE_CASE);
            uint256 burnSeedFold;
            for (uint256 j = 0; j < BURNS_PER_COMPOSE_CASE; ++j) {
                uint256 idx = i * BURNS_PER_COMPOSE_CASE + j;
                bytes32 burnSeed = sampleComposeBurnSeed[idx];
                burnSeedFold ^= uint256(burnSeed);
                burnDonors[j] = GeometrySampling.Donor({
                    id: sampleComposeBurnTokenId[idx],
                    units: Denominations.unitsAt(sampleComposeBurnDenomIndex[idx]),
                    seed: burnSeed,
                    denomIndex: sampleComposeBurnDenomIndex[idx],
                    inkGene: sampleComposeBurnInkGene[idx],
                    modules: sampleComposeBurnModules[idx]
                });
            }
            burnDonors = GeometrySampling.sortDonorsById(burnDonors);

            GeometrySampling.Donor[] memory donors = new GeometrySampling.Donor[](BURNS_PER_COMPOSE_CASE + 1);
            donors[0] = GeometrySampling.Donor({
                id: 0, // the survivor is placed first regardless of id; unused otherwise
                units: Denominations.unitsAt(sampleComposeSurvivorDenomIndex[i]),
                seed: sampleComposeSurvivorSeed[i],
                denomIndex: sampleComposeSurvivorDenomIndex[i],
                inkGene: sampleComposeSurvivorInkGene[i],
                modules: sampleComposeSurvivorModules[i]
            });
            for (uint256 j = 0; j < BURNS_PER_COMPOSE_CASE; ++j) {
                donors[j + 1] = burnDonors[j];
            }

            bytes memory got = GeometrySampling.sampleCompose(
                donors, sampleComposeSurvivorSeed[i], burnSeedFold, sampleComposeNewIndex[i]
            );
            assertEq(got, sampleComposeExpected[i], sampleComposeWhy[i]);
        }
    }

    /// @notice `GeometrySampling.sampleSplitChild` against the TS canonical `sampleSplitChild`
    ///         (SAMPLING_SPEC.md section 6): materialized and seed-derived parents, including
    ///         `childIndex` values that wrap past `uint8` the same way the Solidity cast does.
    function test_SplitSamplingMatchesTypeScript() public view {
        uint256 n = sampleSplitWhy.length;
        assertGt(n, 0, "no split-sampling fixtures");
        for (uint256 i = 0; i < n; ++i) {
            bytes memory parentModules = GeometrySampling.effectiveModulesOf(
                sampleSplitParentModules[i],
                sampleSplitParentSeed[i],
                sampleSplitParentDenomIndex[i],
                sampleSplitParentInkGene[i]
            );
            bytes memory got = GeometrySampling.sampleSplitChild(
                parentModules,
                sampleSplitParentSeed[i],
                sampleSplitChildDenomIndex[i],
                sampleSplitChildIndex[i]
            );
            assertEq(got, sampleSplitExpected[i], sampleSplitWhy[i]);
        }
    }

    /// @notice Sampled render surfaces (grammar v2, SAMPLING_SPEC.md section 7):
    ///         `renderSVGSampled` / `metadataJSONSampled` / `moduleSequenceSampled` against the
    ///         TS canonical, over fixed module byte arrays spanning the 1-module and 20-module
    ///         grids, varied genes, and the full valid kind/rot/solid vocabulary split across
    ///         three arrays.
    function test_SampledRenderSurfacesMatchTypeScript() public view {
        uint256 n = sampledRenderWhy.length;
        assertGt(n, 0, "no sampled-render fixtures");
        for (uint256 i = 0; i < n; ++i) {
            bytes memory modules = sampledRenderModules[i];
            uint256 amountWei = sampledRenderAmountWei[i];
            uint8 gene = sampledRenderInkGene[i];

            string memory svg = renderer.renderSVGSampled(modules, amountWei, sampledRenderInverted[i], gene);
            assertEq(svg, sampledRenderSvg[i], sampledRenderWhy[i]);

            string memory metadata = renderer.metadataJSONSampled(
                modules,
                amountWei,
                sampledRenderTokenId[i],
                sampledRenderOriginCount[i],
                sampledRenderInverted[i],
                gene,
                sampledRenderComposeDepth[i],
                NAME_PREFIX,
                DESCRIPTION
            );
            assertEq(metadata, sampledRenderMetadata[i], sampledRenderWhy[i]);

            string memory modSeq = renderer.moduleSequenceSampled(modules, amountWei, gene);
            assertEq(modSeq, sampledRenderModuleSequence[i], sampledRenderWhy[i]);
        }
    }
}
