/**
 * Writes `preview/src/chain/contractDocs.generated.ts` from the Foundry artifacts in `out/`, so
 * the `/contracts` page documents the real ABI and the real NatSpec and can never be edited into
 * disagreement with the source. Run `forge build` first; the site build itself needs no forge,
 * because the output is committed.
 *
 *   npm run contracts:docs          regenerate
 *   npm run contracts:docs:check    fail if regenerating would change the committed file
 */
import {readFileSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";
import {contractDocFromArtifact, type Artifact, type ContractDoc, type ContractKind} from "../src/chain/contractDocs";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = join(REPO, "out");
const TARGET = join(REPO, "preview", "src", "chain", "contractDocs.generated.ts");

/** Page order: the token, then the two presentation contracts, the application, then libraries. */
const CONTRACTS: {file: string; name: string; kind: ContractKind}[] = [
  {file: "Shapes.sol", name: "Shapes", kind: "token"},
  {file: "ShapeRenderer.sol", name: "ShapeRenderer", kind: "renderer"},
  {file: "ShapeCollection.sol", name: "ShapeCollection", kind: "collection"},
  {file: "ShapeAuctionHouse.sol", name: "ShapeAuctionHouse", kind: "application"},
  {file: "RecompositionOps.sol", name: "RecompositionOps", kind: "library"},
  {file: "AdminOps.sol", name: "AdminOps", kind: "library"},
  {file: "ComposeCompute.sol", name: "ComposeCompute", kind: "library"},
  {file: "GeometrySampling.sol", name: "GeometrySampling", kind: "library"},
  {file: "InkGenes.sol", name: "InkGenes", kind: "library"},
];

function docs(): ContractDoc[] {
  return CONTRACTS.map(({file, name, kind}) => {
    const path = join(OUT, file, `${name}.json`);
    let artifact: Artifact;
    try {
      artifact = JSON.parse(readFileSync(path, "utf8")) as Artifact;
    } catch {
      throw new Error(`missing artifact ${path}; run \`forge build\` first`);
    }
    return contractDocFromArtifact(name, kind, artifact);
  });
}

/** Deterministic JSON: object keys in insertion order, two-space indent, no trailing whitespace. */
function render(all: ContractDoc[]): string {
  return `// Generated by preview/scripts/genContractDocs.ts from the Foundry artifacts in out/.
// Do not edit. Regenerate with \`npm run contracts:docs\` after any ABI or NatSpec change.
import type {ContractDoc} from "./contractDocs";

export const CONTRACT_DOCS: ContractDoc[] = ${JSON.stringify(all, null, 2)};
`;
}

const generated = render(docs());
if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(TARGET, "utf8");
    } catch {
      return "";
    }
  })();
  if (current !== generated) {
    console.error(
      "contractDocs.generated.ts is out of date with out/. Run `npm run contracts:docs` and commit the result.",
    );
    process.exit(1);
  }
  console.log(`ok: contract docs match the artifacts for ${CONTRACTS.length} contracts`);
} else {
  writeFileSync(TARGET, generated);
  console.log(`wrote ${TARGET} for ${CONTRACTS.length} contracts`);
}
