/**
 * Generate the parity fixture corpus.
 *
 * The TypeScript canonical renderer is the specification; these fixtures are its output.
 * The Foundry suite renders the same (seed, amount, tokenId) triples through
 * src/ShapeRenderer.sol and asserts byte-identical strings.
 *
 *   npm run fixtures
 *
 * Written columnar rather than as an array of objects so Foundry can read whole columns
 * with vm.parseJsonStringArray, which is far cheaper than decoding 70 structs.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  composeShape,
  moduleSequence,
  renderShape,
  tokenMetadataJson,
} from "../src/canonical/render";
import { fmt } from "../src/canonical/wad";
import { DENOMINATIONS, LABELS } from "../src/canonical/denominations";
import { CANONICAL, paramsEqualCanonical } from "../src/canonical/params";
import { productionSeed } from "../src/seeds";

if (!paramsEqualCanonical(CANONICAL)) {
  throw new Error("refusing to generate fixtures from non-canonical params");
}

const MAX_U256 = (1n << 256n) - 1n;

interface Case {
  seed: bigint;
  amountWei: bigint;
  tokenId: bigint;
  why: string;
}

const cases: Case[] = [];

// Six production seeds per denomination — the main corpus.
for (let di = 0; di < DENOMINATIONS.length; di++) {
  for (let i = 0; i < 6; i++) {
    const tokenId = BigInt(di * 6 + i + 1);
    cases.push({
      seed: productionSeed(BigInt(di * 1000 + i)),
      amountWei: DENOMINATIONS[di],
      tokenId,
      why: `${LABELS[di]} ETH sample ${i}`,
    });
  }
}

// Edge cases that exercise the formatter, the stream and the id rendering.
const edges: Case[] = [
  { seed: 0n, amountWei: DENOMINATIONS[0], tokenId: 1n, why: "seed zero, densest grid" },
  { seed: 0n, amountWei: DENOMINATIONS[8], tokenId: 1n, why: "seed zero, single module" },
  { seed: MAX_U256, amountWei: DENOMINATIONS[8], tokenId: 1n, why: "seed all ones" },
  { seed: MAX_U256, amountWei: DENOMINATIONS[0], tokenId: 1n, why: "seed all ones, 5x5" },
  {
    // low 32 bits zero, high bits set: proves only the low word reaches the stream
    seed: MAX_U256 ^ 0xffffffffn,
    amountWei: DENOMINATIONS[4],
    tokenId: 7n,
    why: "stream seed zero, high bits set",
  },
  { seed: 0xffffffffn, amountWei: DENOMINATIONS[4], tokenId: 7n, why: "stream seed max" },
  { seed: productionSeed(31337n), amountWei: DENOMINATIONS[7], tokenId: 999_999n, why: "long token id" },
  {
    seed: productionSeed(4242n),
    amountWei: DENOMINATIONS[3],
    tokenId: MAX_U256,
    why: "maximal token id string",
  },
  { seed: productionSeed(1n), amountWei: DENOMINATIONS[6], tokenId: 10n, why: "25 ETH, 2x2" },
  { seed: productionSeed(2n), amountWei: DENOMINATIONS[5], tokenId: 11n, why: "10 ETH, 2x3" },
  { seed: productionSeed(3n), amountWei: DENOMINATIONS[1], tokenId: 12n, why: "0.1 ETH, 4x5" },
  { seed: productionSeed(4n), amountWei: DENOMINATIONS[2], tokenId: 13n, why: "0.5 ETH, 4x4" },
];
cases.push(...edges);

const hex32 = (v: bigint) => "0x" + v.toString(16).padStart(64, "0");

const out = {
  _comment:
    "Generated by preview/scripts/genFixtures.ts from the canonical TypeScript renderer. " +
    "Do not hand-edit. Regenerate with `npm run fixtures` in preview/.",
  count: cases.length,
  why: cases.map((c) => c.why),
  tokenId: cases.map((c) => c.tokenId.toString()),
  seed: cases.map((c) => hex32(c.seed)),
  amountWei: cases.map((c) => c.amountWei.toString()),
  amountLabel: cases.map((c) => LABELS[composeShape(c.seed, c.amountWei).denomIndex] + " ETH"),
  cols: cases.map((c) => composeShape(c.seed, c.amountWei).cols.toString()),
  rows: cases.map((c) => composeShape(c.seed, c.amountWei).rows.toString()),
  cell: cases.map((c) => fmt(composeShape(c.seed, c.amountWei).cell)),
  fill: cases.map((c) => fmt(composeShape(c.seed, c.amountWei).fill)),
  wRatio: cases.map((c) => fmt(composeShape(c.seed, c.amountWei).wRatio)),
  target: cases.map((c) => fmt(composeShape(c.seed, c.amountWei).target)),
  modules: cases.map((c) => moduleSequence(composeShape(c.seed, c.amountWei))),
  svg: cases.map((c) => renderShape(c.seed, c.amountWei, c.tokenId)), // tokenId unused: no type
  metadata: cases.map((c) => tokenMetadataJson(c.seed, c.amountWei, c.tokenId)),
};

const target = resolve(import.meta.dirname, "../../test/fixtures/fixtures.json");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, JSON.stringify(out, null, 1) + "\n");

const bytes = out.svg.reduce((a, s) => a + s.length, 0);
console.log(`wrote ${cases.length} fixtures to ${target}`);
console.log(`  svg bytes: min ${Math.min(...out.svg.map((s) => s.length))}, max ${Math.max(
  ...out.svg.map((s) => s.length),
)}, mean ${Math.round(bytes / cases.length)}`);
