// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";

import {IShapeRenderer} from "./interfaces/IShapeRenderer.sol";
import {Denominations} from "./lib/Denominations.sol";
import {FixedPoint} from "./lib/FixedPoint.sol";
import {Round03Rand} from "./lib/Round03Rand.sol";

/// @title ShapeRenderer
/// @notice Fully onchain SVG and metadata for Shape tokens.
///
/// @dev This contract is a direct port of `preview/src/canonical/render.ts`. Same draw
///      order, same integer arithmetic, same string assembly, same decimal formatting. The
///      parity suite asserts byte-identical output against fixtures generated by that file,
///      so the two cannot drift.
///
///      The renderer is deployed once and referenced immutably by `Shapes`. It has no owner,
///      no setters and no upgrade path. Nothing it emits depends on mutable chain state, so a
///      token's artwork is fixed at mint and cannot change afterwards.
///
///      There is no injection surface: every byte of output comes from a compile-time
///      constant, a fixed lookup table, or `FixedPoint.fmt` over a bounded integer. No
///      caller-supplied text reaches the SVG or the JSON.
contract ShapeRenderer is IShapeRenderer {
    using FixedPoint for uint256;
    using Round03Rand for Round03Rand.Stream;

    /* ------------------------------------------------------------------ *
     *  Round 03 constants. Mirrors preview/src/canonical/params.ts.
     * ------------------------------------------------------------------ */

    // Artwork field, fixed for every denomination.
    uint256 private constant FIELD_W = 198e18;
    uint256 private constant FIELD_H = 230e18;
    uint256 private constant FIELD_CX = 125e18;
    uint256 private constant FIELD_CY = 175e18;  // the card's true centre; there is no type to balance against

    // Size and stroke are collection constants, not per-card draws. FILL is the fraction of
    // the half-cell the painted mark reaches, WRATIO the stroke as a fraction of that painted
    // width. Both are proportional to the cell, so every Shape reads at the same weight at
    // every denomination and the only thing that scales is the grid. 1.0 would be edge to
    // edge; nothing can exceed it.
    uint256 private constant FILL = 0.83e18;
    uint256 private constant WRATIO = 0.14e18;

    uint256 private constant TRI_HEIGHT = 0.866e18;

    // How solid a card is, is drawn per card rather than fixed for the collection: a small
    // share come out entirely outlined, a small share entirely solid, the rest land in a band.
    uint256 private constant PURE_OUTLINE_CHANCE = 0.05e18;
    uint256 private constant PURE_SOLID_CHANCE = 0.05e18;
    uint256 private constant SOLID_BAND_MIN = 0.30e18;
    uint256 private constant SOLID_BAND_MAX = 0.90e18;

    /// @dev sqrt(2), for the diagonal line's 45 degree cap and the diamond's inner-ring inset.
    uint256 private constant SQRT2 = 1_414_213_562_373_095_048;
    /// @dev 2 - sqrt(2), the right triangle's inradius as a fraction of its leg half-length.
    uint256 private constant TWO_MINUS_SQRT2 = 585_786_437_626_904_952;

    // Vocabulary. The order is consensus-critical, because kind selection indexes into it.
    //
    // Ten primitives. Circle, square and diamond are rotation-invariant and take a solid and an
    // outlined form: two appearances each. Triangle, half circle, quarter circle, half square,
    // right triangle and arc each take one of four rotations; the diagonal line takes one of
    // two. Arc and line are open strokes: outlined only, no solid form. 52 distinct module
    // appearances in total.
    //
    // Half square is the rectangular twin of the half circle: half the cell, split by a
    // straight edge. Right triangle is the square cut on its diagonal. Arc is the quarter
    // disc's curved edge alone, with no straight radii; line is the cell diagonal.
    //
    // There is deliberately no separate "ring". A ring is a circle with a heavier stroke, and
    // carrying it as its own primitive meant one mark on a card ignored the card's stroke
    // weight and used a hard-coded 0.22 x d instead — 1.3x to 2.2x heavier than the outlined
    // circle beside it, for no reason a viewer could infer. One stroke weight per card.
    uint256 private constant KIND_CIRCLE = 0;
    uint256 private constant KIND_SQUARE = 1;
    uint256 private constant KIND_TRIANGLE = 2;
    uint256 private constant KIND_HALF = 3;
    uint256 private constant KIND_QUARTER = 4;
    uint256 private constant KIND_DIAMOND = 5;
    uint256 private constant KIND_HALFSQUARE = 6;
    uint256 private constant KIND_RTRIANGLE = 7;
    uint256 private constant KIND_ARC = 8;
    uint256 private constant KIND_LINE = 9;
    uint256 private constant KIND_COUNT = 10;

    string private constant DESCRIPTION =
        "Shapes are ETH-backed onchain objects. Each Shape wraps an exact amount of ETH; "
        "burning it returns exactly that amount to its owner. Value sets the grammar, the "
        "seed writes the sentence: higher denominations resolve into fewer, larger modules. "
        "Artwork and metadata are generated entirely onchain.";

    /* ------------------------------------------------------------------ *
     *  Composition
     * ------------------------------------------------------------------ */

    struct Module {
        uint256 kind;
        bool solid;
        uint256 rot; // 0, 90, 180 or 270, clockwise
        uint256 cx;
        uint256 cy;
        /// @dev The path footprint handed to the drawing primitive — a diameter, a side, or a
        ///      triangle's base. Solved backwards from `target` so the painted result, stroke
        ///      and miter joins included, reaches exactly `target` from the cell centre.
        uint256 size;
        uint256 weight; // stroke weight, one per card, drawn only when !solid
    }

    struct Card {
        uint256 denomIndex;
        uint256 cols;
        uint256 rows;
        uint256 cell;
        uint256 fill;
        uint256 wRatio;
        /// @dev Painted half-extent every module on this card reaches, in user units.
        uint256 target;
        uint256 weight;
        /// @dev This card's own probability that any given module comes out solid.
        uint256 solidProbability;
        Module[] modules;
    }

    /// @dev Grid geometry, derived from the denomination. Never hand-placed.
    struct Geometry {
        uint256 cols;
        uint256 rows;
        uint256 cell;
        uint256 x0;
        uint256 y0;
        uint256 halfCell;
    }

    function _geometry(uint256 di) private pure returns (Geometry memory g) {
        (g.cols, g.rows) = Denominations.gridAt(di);
        g.cell = FixedPoint.min(FIELD_W / g.cols, FIELD_H / g.rows);
        g.x0 = FIELD_CX - (g.cols * g.cell) / 2;
        g.y0 = FIELD_CY - (g.rows * g.cell) / 2;
        g.halfCell = g.cell / 2;
    }

    /// @dev Distinct rotations a kind takes: 1 (rotation-invariant), 2 (the diagonal line), or 4.
    function _rotCount(uint256 kind) private pure returns (uint256) {
        if (kind == KIND_CIRCLE || kind == KIND_SQUARE || kind == KIND_DIAMOND) return 1;
        if (kind == KIND_LINE) return 2;
        return 4;
    }

    /// @dev One cell. Draws in the order kind -> solid -> rotation, consuming `rotation` only
    ///      for kinds with more than one orientation. `nextBelow` consumes a single stream value
    ///      whatever the bound, so a two-way kind stays aligned with the four-way ones.
    function _module(
        Round03Rand.Stream memory rnd,
        uint256 i,
        Geometry memory g,
        uint256 target,
        uint256 weight,
        uint256 solidProbability
    ) private pure returns (Module memory m) {
        m.kind = rnd.nextBelow(KIND_COUNT);
        m.solid = rnd.nextBelowProbability(solidProbability);
        uint256 rc = _rotCount(m.kind);
        m.rot = rc > 1 ? rnd.nextBelow(rc) * 90 : 0;

        m.weight = weight;
        m.size = _solveSize(m.kind, m.solid, target, weight);

        m.cx = g.x0 + (i % g.cols) * g.cell + g.halfCell;
        m.cy = g.y0 + (i / g.cols) * g.cell + g.halfCell;
    }

    /// @dev Map a uniform draw onto this card's solid probability.
    ///
    ///      A single global solid rate makes every card the same mixture. Drawing the rate per
    ///      card instead gives the collection a shape: a small share come out entirely
    ///      outlined, a small share entirely solid, and the rest land in a band. Both extremes
    ///      are exact — a card that draws 0 contains no solid mark at all — which is why the
    ///      per-module test is `draw < p` rather than `draw > t`.
    ///
    ///        r <  PURE_OUTLINE_CHANCE     -> 0    every module outlined
    ///        r >= 1 - PURE_SOLID_CHANCE   -> 1    every module solid
    ///        otherwise                    -> remapped linearly onto the band
    function _drawSolidProbability(uint256 r) private pure returns (uint256) {
        if (r < PURE_OUTLINE_CHANCE) return 0;
        uint256 upper = FixedPoint.WAD - PURE_SOLID_CHANCE;
        if (r >= upper) return FixedPoint.WAD;

        uint256 span = upper - PURE_OUTLINE_CHANCE;
        uint256 t = ((r - PURE_OUTLINE_CHANCE) * FixedPoint.WAD) / span;
        return SOLID_BAND_MIN + t.mulWad(SOLID_BAND_MAX - SOLID_BAND_MIN);
    }

    /// @dev How this card came out of the fill draw. A single mark can only come out one way, so
    ///      a lone module reports its actual fill rather than the card's regime (which would read
    ///      "Mixed" while only one fill is drawn). Otherwise, Solid and Outline are the extremes.
    function _fillClass(Card memory card) private pure returns (string memory) {
        if (card.modules.length == 1) return card.modules[0].solid ? "Solid" : "Outline";
        if (card.solidProbability == 0) return "Outline";
        if (card.solidProbability == FixedPoint.WAD) return "Solid";
        return "Mixed";
    }

    /// @dev Solve the path footprint that paints to exactly `target` from the cell centre.
    ///
    ///      A solid mark paints to its own edge, so its footprint is `2 * target`. Outlined
    ///      marks come in two constructions:
    ///
    ///        circle, square, halfsquare    drawn as a stroked path. The stroke straddles the
    ///                                      edge, adding w/2 all round, and every painted
    ///                                      extent — 90 degree miter corners included — lands
    ///                                      exactly on the target -> size = 2 * target - w
    ///
    ///        triangle, rtriangle, diamond, drawn as an even-odd ring whose outer boundary is
    ///        half, quarter                 the solid geometry itself, so every edge sits
    ///                                      exactly where the solid form's does; the inner
    ///                                      boundary is inset by the weight -> size = 2 * target
    ///
    ///        arc, line                     filled bands of one weight, never solid. Both span
    ///                                      the full footprint: the arc's outer curve connects
    ///                                      two footprint corners, the line's tips are clipped
    ///                                      into the other two -> size = 2 * target
    function _solveSize(uint256 kind, bool solid, uint256 target, uint256 weight)
        private
        pure
        returns (uint256)
    {
        uint256 full = 2 * target;
        if (kind == KIND_ARC || kind == KIND_LINE) return full;
        if (solid) return full;
        if (kind == KIND_CIRCLE || kind == KIND_SQUARE || kind == KIND_HALFSQUARE) {
            return full - weight;
        }
        return full;
    }

    /// @notice Resolve a token into its full geometric description.
    /// @dev Draw order, consensus critical (SPEC.md D5):
    ///        1. fill     — always
    ///        2. wRatio   — always
    ///      then per cell, row-major:
    ///        3. kind     — always
    ///        3. solid probability — always
    ///      then per cell:
    ///        4. kind     — always
    ///        5. solid    — always
    ///        5. rotation — only when the kind takes more than one orientation
    ///      The conditional consumption is load-bearing. Drawing unconditionally would
    ///      desynchronise the stream and change every subsequent cell on the card.
    function compose(bytes32 seed, uint256 amountWei) public pure returns (Card memory card) {
        uint256 di = Denominations.requireIndexOf(amountWei);
        Geometry memory g = _geometry(di);
        Round03Rand.Stream memory rnd = Round03Rand.init(seed);

        card.denomIndex = di;
        card.cols = g.cols;
        card.rows = g.rows;
        card.cell = g.cell;
        card.fill = FILL;
        card.wRatio = WRATIO;
        card.target = g.halfCell.mulWad(FILL);
        card.weight = (2 * card.target).mulWad(card.wRatio);
        card.solidProbability = _drawSolidProbability(rnd.nextWad());

        uint256 n = g.cols * g.rows;
        card.modules = new Module[](n);
        for (uint256 i = 0; i < n; ++i) {
            card.modules[i] = _module(rnd, i, g, card.target, card.weight, card.solidProbability);
        }
    }

    /* ------------------------------------------------------------------ *
     *  SVG
     * ------------------------------------------------------------------ */

    function _style(bool solid, uint256 weight, string memory fg)
        private
        pure
        returns (bytes memory)
    {
        return solid
            ? abi.encodePacked(' fill="', fg, '"/>')
            : abi.encodePacked(
                ' fill="none" stroke="', fg, '" stroke-width="', weight.fmt(), '"/>'
            );
    }

    function _transform(uint256 rot, uint256 cx, uint256 cy) private pure returns (bytes memory) {
        if (rot == 0) return "";
        return abi.encodePacked(
            ' transform="rotate(', FixedPoint.toString(rot), " ", cx.fmt(), " ", cy.fmt(), ')"'
        );
    }

    /// @dev An outlined mark built as a filled even-odd ring: the outer subpath is the solid
    ///      geometry itself, the inner subpath the same shape inset by the stroke weight. Every
    ///      painted edge sits exactly where the solid form's does — no stroke, no miter join.
    function _ring(bytes memory d, uint256 rot, uint256 cx, uint256 cy, string memory fg)
        private
        pure
        returns (bytes memory)
    {
        return abi.encodePacked(
            '<path fill-rule="evenodd" d="', d, '"', _transform(rot, cx, cy), ' fill="', fg, '"/>'
        );
    }

    /// @dev divWad(a - b, a), clamped to zero when the inset would consume the shape.
    function _insetScale(uint256 a, uint256 b) private pure returns (uint256) {
        return a > b ? (a - b).divWad(a) : 0;
    }

    function _moduleSvg(Module memory m, string memory fg) private pure returns (bytes memory) {
        uint256 r = m.size / 2;

        if (m.kind == KIND_CIRCLE) {
            return abi.encodePacked(
                '<circle cx="', m.cx.fmt(), '" cy="', m.cy.fmt(), '" r="', r.fmt(), '"',
                _style(m.solid, m.weight, fg)
            );
        }

        if (m.kind == KIND_SQUARE) {
            return abi.encodePacked(
                '<rect x="', (m.cx - r).fmt(), '" y="', (m.cy - r).fmt(),
                '" width="', m.size.fmt(), '" height="', m.size.fmt(), '"',
                _style(m.solid, m.weight, fg)
            );
        }

        if (m.kind == KIND_TRIANGLE) {
            uint256 hh = m.size.mulWad(TRI_HEIGHT);
            uint256 half = hh / 2;
            bytes memory outer = abi.encodePacked(
                "M", m.cx.fmt(), ",", (m.cy - half).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy + half).fmt(),
                " L", (m.cx - r).fmt(), ",", (m.cy + half).fmt(), " Z"
            );
            if (m.solid) {
                return abi.encodePacked(
                    '<polygon points="',
                    m.cx.fmt(), ",", (m.cy - half).fmt(), " ",
                    (m.cx + r).fmt(), ",", (m.cy + half).fmt(), " ",
                    (m.cx - r).fmt(), ",", (m.cy + half).fmt(),
                    '"',
                    _transform(m.rot, m.cx, m.cy),
                    _style(true, m.weight, fg)
                );
            }
            // Inner triangle: the outer scaled about the incenter, which offsets every edge
            // inward by the weight. Incenter sits one third of the height above the base;
            // inradius = h/3.
            uint256 rho = hh / 3;
            uint256 k = _insetScale(rho, m.weight);
            uint256 iy = m.cy + half - rho;
            bytes memory inner = abi.encodePacked(
                "M", m.cx.fmt(), ",", (iy - k.mulWad(hh - rho)).fmt(),
                " L", (m.cx + k.mulWad(r)).fmt(), ",", (iy + k.mulWad(rho)).fmt(),
                " L", (m.cx - k.mulWad(r)).fmt(), ",", (iy + k.mulWad(rho)).fmt(), " Z"
            );
            return _ring(abi.encodePacked(outer, " ", inner), m.rot, m.cx, m.cy, fg);
        }

        if (m.kind == KIND_QUARTER) {
            // A quarter disc whose right-angle corner sits at one corner of the footprint and
            // whose arc sweeps to the opposite two: a square with one corner rounded away.
            // The arc radius is the full footprint, not half of it.
            uint256 R = m.size;
            bytes memory outer = abi.encodePacked(
                "M", (m.cx - r).fmt(), ",", (m.cy + r).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy + r).fmt(),
                " A", R.fmt(), ",", R.fmt(), " 0 0 0 ",
                (m.cx - r).fmt(), ",", (m.cy - r).fmt(), " Z"
            );
            if (m.solid) {
                return abi.encodePacked(
                    '<path d="', outer, '"',
                    _transform(m.rot, m.cx, m.cy),
                    _style(true, m.weight, fg)
                );
            }
            // Inner region: legs offset inward by the weight, arc of radius R - w about the
            // same corner, meeting each offset leg where the circle crosses it.
            uint256 Ri = R - m.weight;
            uint256 q = (Ri * Ri - m.weight * m.weight).isqrt();
            bytes memory inner = abi.encodePacked(
                "M", (m.cx - r + m.weight).fmt(), ",", (m.cy + r - m.weight).fmt(),
                " L", (m.cx - r + q).fmt(), ",", (m.cy + r - m.weight).fmt(),
                " A", Ri.fmt(), ",", Ri.fmt(), " 0 0 0 ",
                (m.cx - r + m.weight).fmt(), ",", (m.cy + r - q).fmt(), " Z"
            );
            return _ring(abi.encodePacked(outer, " ", inner), m.rot, m.cx, m.cy, fg);
        }

        if (m.kind == KIND_DIAMOND) {
            if (m.solid) {
                // The square on its diagonal, emitted as its four vertices so the geometry is
                // explicit in one place. Never rotated.
                return abi.encodePacked(
                    '<polygon points="',
                    m.cx.fmt(), ",", (m.cy - r).fmt(), " ",
                    (m.cx + r).fmt(), ",", m.cy.fmt(), " ",
                    m.cx.fmt(), ",", (m.cy + r).fmt(), " ",
                    (m.cx - r).fmt(), ",", m.cy.fmt(),
                    '"',
                    _style(true, m.weight, fg)
                );
            }
            // Inner diamond: edges offset inward by the weight shorten the half-diagonal by
            // w * sqrt(2).
            uint256 ri = r > SQRT2.mulWad(m.weight) ? r - SQRT2.mulWad(m.weight) : 0;
            bytes memory d = abi.encodePacked(
                "M", m.cx.fmt(), ",", (m.cy - r).fmt(), " L", (m.cx + r).fmt(), ",", m.cy.fmt(),
                " L", m.cx.fmt(), ",", (m.cy + r).fmt(), " L", (m.cx - r).fmt(), ",", m.cy.fmt(),
                " Z ",
                "M", m.cx.fmt(), ",", (m.cy - ri).fmt(), " L", (m.cx + ri).fmt(), ",", m.cy.fmt(),
                " L", m.cx.fmt(), ",", (m.cy + ri).fmt(), " L", (m.cx - ri).fmt(), ",", m.cy.fmt(),
                " Z"
            );
            return _ring(d, 0, m.cx, m.cy, fg);
        }

        if (m.kind == KIND_HALFSQUARE) {
            // Half the cell, split by a straight edge: a rectangle filling the upper half of the
            // footprint at rotation 0. The rectangular twin of the half circle.
            return abi.encodePacked(
                '<rect x="', (m.cx - r).fmt(), '" y="', (m.cy - r).fmt(),
                '" width="', m.size.fmt(), '" height="', r.fmt(), '"',
                _transform(m.rot, m.cx, m.cy),
                _style(m.solid, m.weight, fg)
            );
        }

        if (m.kind == KIND_RTRIANGLE) {
            if (m.solid) {
                // The square cut on its diagonal: right angle at the top-left footprint corner
                // at rotation 0, hypotenuse from top-right to bottom-left.
                return abi.encodePacked(
                    '<polygon points="',
                    (m.cx - r).fmt(), ",", (m.cy - r).fmt(), " ",
                    (m.cx + r).fmt(), ",", (m.cy - r).fmt(), " ",
                    (m.cx - r).fmt(), ",", (m.cy + r).fmt(),
                    '"',
                    _transform(m.rot, m.cx, m.cy),
                    _style(true, m.weight, fg)
                );
            }
            // Inner triangle: the outer scaled about the incenter, which offsets every edge
            // inward by the weight. For a right isoceles triangle with legs 2r, inradius =
            // r * (2 - sqrt(2)); the incenter sits that far from each leg.
            uint256 rho = r.mulWad(TWO_MINUS_SQRT2);
            uint256 k = _insetScale(rho, m.weight);
            uint256 ix = m.cx - r + rho;
            uint256 iy = m.cy - r + rho;
            uint256 near = k.mulWad(rho); // incenter to the right-angle vertex, scaled
            uint256 far = k.mulWad(2 * r - rho); // incenter to each acute vertex, scaled
            bytes memory d = abi.encodePacked(
                "M", (m.cx - r).fmt(), ",", (m.cy - r).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy - r).fmt(),
                " L", (m.cx - r).fmt(), ",", (m.cy + r).fmt(), " Z ",
                "M", (ix - near).fmt(), ",", (iy - near).fmt(),
                " L", (ix + far).fmt(), ",", (iy - near).fmt(),
                " L", (ix - near).fmt(), ",", (iy + far).fmt(), " Z"
            );
            return _ring(d, m.rot, m.cx, m.cy, fg);
        }

        if (m.kind == KIND_ARC) {
            // The quarter disc's curved edge alone: a filled annular band one weight thick.
            // The outer curve has the footprint for its radius and connects two footprint
            // corners; the band's flat radial ends lie on the footprint edges.
            uint256 arcRi = m.size - m.weight;
            return abi.encodePacked(
                '<path d="M', (m.cx + r).fmt(), ",", (m.cy + r).fmt(),
                " A", m.size.fmt(), ",", m.size.fmt(), " 0 0 0 ",
                (m.cx - r).fmt(), ",", (m.cy - r).fmt(),
                " L", (m.cx - r).fmt(), ",", (m.cy - r + m.weight).fmt(),
                " A", arcRi.fmt(), ",", arcRi.fmt(), " 0 0 1 ",
                (m.cx + r - m.weight).fmt(), ",", (m.cy + r).fmt(), ' Z"',
                _transform(m.rot, m.cx, m.cy),
                ' fill="', fg, '"/>'
            );
        }

        if (m.kind == KIND_LINE) {
            // A straight diagonal band across the cell, one weight thick, its centreline the
            // footprint diagonal. The tips are clipped by the footprint square, so each ends
            // in a point exactly on the corner. Two orientations.
            uint256 o = m.weight.mulWad(SQRT2) / 2;
            return abi.encodePacked(
                '<path d="M', (m.cx - r + o).fmt(), ",", (m.cy - r).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy + r - o).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy + r).fmt(),
                " L", (m.cx + r - o).fmt(), ",", (m.cy + r).fmt(),
                " L", (m.cx - r).fmt(), ",", (m.cy - r + o).fmt(),
                " L", (m.cx - r).fmt(), ",", (m.cy - r).fmt(), ' Z"',
                _transform(m.rot, m.cx, m.cy),
                ' fill="', fg, '"/>'
            );
        }

        // half circle: flat edge through the cell centre, filled half above at rotation 0
        {
            bytes memory outer = abi.encodePacked(
                "M", (m.cx - r).fmt(), ",", m.cy.fmt(),
                " A", r.fmt(), ",", r.fmt(), " 0 0 1 ", (m.cx + r).fmt(), ",", m.cy.fmt(), " Z"
            );
            if (m.solid) {
                return abi.encodePacked(
                    '<path d="', outer, '"',
                    _transform(m.rot, m.cx, m.cy),
                    _style(true, m.weight, fg)
                );
            }
            // Inner region: the half disc's points at least `weight` from its boundary — an
            // arc of radius r - w about the same centre, chorded where it meets the offset
            // flat edge.
            uint256 ri = r - m.weight;
            uint256 q = (ri * ri - m.weight * m.weight).isqrt();
            bytes memory inner = abi.encodePacked(
                "M", (m.cx - q).fmt(), ",", (m.cy - m.weight).fmt(),
                " A", ri.fmt(), ",", ri.fmt(), " 0 0 1 ", (m.cx + q).fmt(), ",", (m.cy - m.weight).fmt(), " Z"
            );
            return _ring(abi.encodePacked(outer, " ", inner), m.rot, m.cx, m.cy, fg);
        }
    }

    /// @inheritdoc IShapeRenderer
    /// @dev A Shape carries no type: a field, marks, nothing else. The denomination and the token
    ///      number live in the metadata, not on the card face. `inverted` swaps the field and mark
    ///      colors: false is a dark field with light marks, true is the exact inverse used by the
    ///      Black Shape. Geometry and coordinates are identical between the two.
    function renderSVG(bytes32 seed, uint256 amountWei, bool inverted)
        public
        pure
        returns (string memory)
    {
        Card memory card = compose(seed, amountWei);

        string memory bg = inverted ? "#fff" : "#000";
        string memory fg = inverted ? "#000" : "#fff";

        bytes memory body;
        uint256 n = card.modules.length;
        for (uint256 i = 0; i < n; ++i) {
            body = abi.encodePacked(body, _moduleSvg(card.modules[i], fg));
        }

        return string(
            abi.encodePacked(
                // width/height set the intrinsic raster size (8x the viewBox); geometry is in
                // viewBox units, so the look is identical at any scale.
                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 350"'
                ' width="2000" height="2800" shape-rendering="geometricPrecision">'
                '<rect x="0" y="0" width="250" height="350" fill="',
                bg,
                '"/>',
                body,
                "</svg>"
            )
        );
    }

    /* ------------------------------------------------------------------ *
     *  Module glyph sequence
     * ------------------------------------------------------------------ */

    /// @dev Glyphs from the Geometric Shapes block, matching the vocabulary of Round 04 of
    ///      the same design exploration. Derived from the composition, never re-rolled, so
    ///      the trait and the artwork always describe the same token (SPEC.md D10).
    function _glyph(Module memory m) private pure returns (string memory) {
        if (m.kind == KIND_CIRCLE) return m.solid ? unicode"●" : unicode"○";
        if (m.kind == KIND_SQUARE) return m.solid ? unicode"■" : unicode"□";
        if (m.kind == KIND_QUARTER) return m.solid ? unicode"◔" : unicode"◷";
        if (m.kind == KIND_DIAMOND) return m.solid ? unicode"◆" : unicode"◇";
        if (m.kind == KIND_TRIANGLE) {
            if (m.solid) {
                if (m.rot == 0) return unicode"▲";
                if (m.rot == 90) return unicode"▶";
                if (m.rot == 180) return unicode"▼";
                return unicode"◀";
            }
            if (m.rot == 0) return unicode"△";
            if (m.rot == 90) return unicode"▷";
            if (m.rot == 180) return unicode"▽";
            return unicode"◁";
        }
        if (m.kind == KIND_HALFSQUARE) {
            if (m.rot == 0) return unicode"⬒";
            if (m.rot == 90) return unicode"◨";
            if (m.rot == 180) return unicode"⬓";
            return unicode"◧";
        }
        if (m.kind == KIND_RTRIANGLE) {
            if (m.rot == 0) return unicode"◸";
            if (m.rot == 90) return unicode"◹";
            if (m.rot == 180) return unicode"◿";
            return unicode"◺";
        }
        if (m.kind == KIND_ARC) {
            if (m.rot == 0) return unicode"◜";
            if (m.rot == 90) return unicode"◝";
            if (m.rot == 180) return unicode"◞";
            return unicode"◟";
        }
        if (m.kind == KIND_LINE) {
            return m.rot == 0 ? unicode"╲" : unicode"╱";
        }
        if (m.rot == 0) return unicode"◓";
        if (m.rot == 90) return unicode"◑";
        if (m.rot == 180) return unicode"◒";
        return unicode"◐";
    }

    function _moduleSequence(Card memory card) private pure returns (bytes memory out) {
        uint256 n = card.modules.length;
        for (uint256 i = 0; i < n; ++i) {
            out = i == 0
                ? bytes(_glyph(card.modules[i]))
                : abi.encodePacked(out, " ", _glyph(card.modules[i]));
        }
    }

    /// @inheritdoc IShapeRenderer
    function moduleSequence(bytes32 seed, uint256 amountWei) external pure returns (string memory) {
        return string(_moduleSequence(compose(seed, amountWei)));
    }

    /* ------------------------------------------------------------------ *
     *  Metadata
     * ------------------------------------------------------------------ */

    function _hex32(bytes32 v) private pure returns (bytes memory out) {
        bytes memory alphabet = "0123456789abcdef";
        out = new bytes(66);
        out[0] = "0";
        out[1] = "x";
        for (uint256 i = 0; i < 32; ++i) {
            out[2 + i * 2] = alphabet[uint8(v[i]) >> 4];
            out[3 + i * 2] = alphabet[uint8(v[i]) & 0x0f];
        }
    }

    /// @dev The provenance label derived from `(units, originCount, isBlack)`. `units` is the
    ///      backing's 0.01 count. Black takes precedence; then Complete (an origin per unit, above
    ///      the minimum tier); then Fragment (zero origins — a decompose remainder credited none);
    ///      then Direct (a single origin) vs Composed. Fragment is distinct so a zero-origin split
    ///      remainder is not labelled "Composed", which would assert a history it does not have.
    function _formation(uint256 units, uint256 originCount, bool isBlack)
        private
        pure
        returns (string memory)
    {
        if (isBlack) return "Black";
        if (units > 1 && originCount == units) return "Complete";
        if (originCount == 0) return "Fragment";
        if (originCount == 1) return "Direct";
        return "Composed";
    }

    /// @dev `originCount / units` as a percentage string with trailing zeros trimmed, e.g. "100",
    ///      "20", "1", "0.2", "0.01". Every unit count divides 10000, so the hundredths are exact.
    function _densityPercent(uint256 units, uint256 originCount)
        private
        pure
        returns (bytes memory)
    {
        uint256 h = (originCount * 10000) / units; // percentage in hundredths: 10000 == 100.00%
        uint256 whole = h / 100;
        uint256 frac = h % 100;
        if (frac == 0) return bytes(FixedPoint.toString(whole));
        if (frac % 10 == 0) {
            return abi.encodePacked(FixedPoint.toString(whole), ".", FixedPoint.toString(frac / 10));
        }
        bytes memory two = frac < 10
            ? abi.encodePacked("0", FixedPoint.toString(frac))
            : bytes(FixedPoint.toString(frac));
        return abi.encodePacked(FixedPoint.toString(whole), ".", two);
    }

    /// @inheritdoc IShapeRenderer
    function metadataJSON(
        bytes32 seed,
        uint256 amountWei,
        uint256 tokenId,
        uint256 originCount,
        bool inverted
    ) public pure returns (string memory) {
        Card memory card = compose(seed, amountWei);
        string memory svg = renderSVG(seed, amountWei, inverted);

        uint256 units = Denominations.unitsAt(card.denomIndex);
        bool complete = !inverted && units > 1 && originCount == units;

        return string(
            abi.encodePacked(
                '{"name":"Shape #',
                FixedPoint.toString(tokenId),
                '","description":"',
                DESCRIPTION,
                '","image":"data:image/svg+xml;base64,',
                Base64.encode(bytes(svg)),
                '","attributes":[{"trait_type":"ETH Value","value":"',
                Denominations.labelAt(card.denomIndex),
                ' ETH"},{"trait_type":"Grid","value":"',
                FixedPoint.toString(card.cols),
                "x",
                FixedPoint.toString(card.rows),
                '"},{"trait_type":"Fill","value":"',
                _fillClass(card),
                '"},{"trait_type":"Modules","value":"',
                _moduleSequence(card),
                '"},{"trait_type":"Module Count","value":',
                FixedPoint.toString(card.cols * card.rows),
                _provenanceTraits(units, originCount, complete, inverted),
                ',{"trait_type":"Seed","value":"',
                _hex32(seed),
                '"}]}'
            )
        );
    }

    /// @dev The provenance trait block, split out to keep `metadataJSON` under the stack limit.
    ///      Formation, Independent Origins, Origin Density (percent), Complete and Black.
    function _provenanceTraits(uint256 units, uint256 originCount, bool complete, bool isBlack)
        private
        pure
        returns (bytes memory)
    {
        return abi.encodePacked(
            '},{"trait_type":"Formation","value":"',
            _formation(units, originCount, isBlack),
            '"},{"trait_type":"Independent Origins","value":',
            FixedPoint.toString(originCount),
            '},{"trait_type":"Origin Density","value":"',
            _densityPercent(units, originCount),
            '%"},{"trait_type":"Complete","value":"',
            complete ? "true" : "false",
            '"},{"trait_type":"Black","value":"',
            isBlack ? "true" : "false",
            '"}'
        );
    }

    /// @inheritdoc IShapeRenderer
    function tokenURI(
        bytes32 seed,
        uint256 amountWei,
        uint256 tokenId,
        uint256 originCount,
        bool inverted
    ) external pure returns (string memory) {
        return string(
            abi.encodePacked(
                "data:application/json;base64,",
                Base64.encode(bytes(metadataJSON(seed, amountWei, tokenId, originCount, inverted)))
            )
        );
    }
}
