// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Base64} from "@openzeppelin/contracts/utils/Base64.sol";

import {IShapeRenderer} from "./interfaces/IShapeRenderer.sol";
import {Denominations} from "./lib/Denominations.sol";
import {FixedPoint} from "./lib/FixedPoint.sol";
import {Round03Rand} from "./lib/Round03Rand.sol";

/// @title ShapeRenderer
/// @notice Fully onchain SVG and metadata for Shape tokens.
///
/// @dev This contract is a direct port of `preview/src/canonical/render.ts`. Same draw
///      order, same integer arithmetic, same string assembly, same decimal formatting. The
///      parity suite asserts byte-identical output against fixtures generated by that file,
///      so the two cannot drift.
///
///      The renderer is deployed once and referenced immutably by `Shapes`. It has no owner,
///      no setters and no upgrade path. Nothing it emits depends on mutable chain state, so a
///      token's artwork is fixed at mint and cannot change afterwards.
///
///      There is no injection surface: every byte of output comes from a compile-time
///      constant, a fixed lookup table, or `FixedPoint.fmt` over a bounded integer. No
///      caller-supplied text reaches the SVG or the JSON.
contract ShapeRenderer is IShapeRenderer {
    using FixedPoint for uint256;
    using Round03Rand for Round03Rand.Stream;

    /* ------------------------------------------------------------------ *
     *  Round 03 constants. Mirrors preview/src/canonical/params.ts.
     * ------------------------------------------------------------------ */

    // Artwork field, fixed for every denomination.
    uint256 private constant FIELD_W = 198e18;
    uint256 private constant FIELD_H = 230e18;
    uint256 private constant FIELD_CX = 125e18;
    uint256 private constant FIELD_CY = 175e18;  // the card's true centre; there is no type to balance against

    // Size and stroke are collection constants, not per-card draws. FILL is the fraction of
    // the half-cell the painted mark reaches, WRATIO the stroke as a fraction of that painted
    // width. Both are proportional to the cell, so every Shape reads at the same weight at
    // every denomination and the only thing that scales is the grid. 1.0 would be edge to
    // edge; nothing can exceed it.
    uint256 private constant FILL = 0.83e18;
    uint256 private constant WRATIO = 0.14e18;

    uint256 private constant TRI_HEIGHT = 0.866e18;

    // How solid a card is, is drawn per card rather than fixed for the collection: a small
    // share come out entirely outlined, a small share entirely solid, the rest land in a band.
    uint256 private constant PURE_OUTLINE_CHANCE = 0.05e18;
    uint256 private constant PURE_SOLID_CHANCE = 0.05e18;
    uint256 private constant SOLID_BAND_MIN = 0.30e18;
    uint256 private constant SOLID_BAND_MAX = 0.90e18;

    /// @dev sqrt(3), used to invert a triangle's 60 degree miter overshoot.
    uint256 private constant SQRT3 = 1_732_050_807_568_877_293;
    /// @dev sqrt(2) and 1 + sqrt(2), for the diagonal line's 45 degree cap and the right
    ///      triangle's 45 degree miter.
    uint256 private constant SQRT2 = 1_414_213_562_373_095_048;
    uint256 private constant ONE_PLUS_SQRT2 = 2_414_213_562_373_095_048;

    // Vocabulary. The order is consensus-critical, because kind selection indexes into it.
    //
    // Ten primitives. Circle, square and diamond are rotation-invariant and take a solid and an
    // outlined form: two appearances each. Triangle, half circle, quarter circle, half square,
    // right triangle and arc each take one of four rotations; the diagonal line takes one of
    // two. Arc and line are open strokes: outlined only, no solid form. 52 distinct module
    // appearances in total.
    //
    // Half square is the rectangular twin of the half circle: half the cell, split by a
    // straight edge. Right triangle is the square cut on its diagonal. Arc is the quarter
    // disc's curved edge alone, with no straight radii; line is the cell diagonal.
    //
    // There is deliberately no separate "ring". A ring is a circle with a heavier stroke, and
    // carrying it as its own primitive meant one mark on a card ignored the card's stroke
    // weight and used a hard-coded 0.22 x d instead — 1.3x to 2.2x heavier than the outlined
    // circle beside it, for no reason a viewer could infer. One stroke weight per card.
    uint256 private constant KIND_CIRCLE = 0;
    uint256 private constant KIND_SQUARE = 1;
    uint256 private constant KIND_TRIANGLE = 2;
    uint256 private constant KIND_HALF = 3;
    uint256 private constant KIND_QUARTER = 4;
    uint256 private constant KIND_DIAMOND = 5;
    uint256 private constant KIND_HALFSQUARE = 6;
    uint256 private constant KIND_RTRIANGLE = 7;
    uint256 private constant KIND_ARC = 8;
    uint256 private constant KIND_LINE = 9;
    uint256 private constant KIND_COUNT = 10;

    string private constant DESCRIPTION =
        "Shapes are ETH-backed onchain objects. Each Shape wraps an exact amount of ETH; "
        "burning it returns exactly that amount to its owner. Value sets the grammar, the "
        "seed writes the sentence: higher denominations resolve into fewer, larger modules. "
        "Artwork and metadata are generated entirely onchain.";

    /* ------------------------------------------------------------------ *
     *  Composition
     * ------------------------------------------------------------------ */

    struct Module {
        uint256 kind;
        bool solid;
        uint256 rot; // 0, 90, 180 or 270, clockwise
        uint256 cx;
        uint256 cy;
        /// @dev The path footprint handed to the drawing primitive — a diameter, a side, or a
        ///      triangle's base. Solved backwards from `target` so the painted result, stroke
        ///      and miter joins included, reaches exactly `target` from the cell centre.
        uint256 size;
        uint256 weight; // stroke weight, one per card, drawn only when !solid
    }

    struct Card {
        uint256 denomIndex;
        uint256 cols;
        uint256 rows;
        uint256 cell;
        uint256 fill;
        uint256 wRatio;
        /// @dev Painted half-extent every module on this card reaches, in user units.
        uint256 target;
        uint256 weight;
        /// @dev This card's own probability that any given module comes out solid.
        uint256 solidProbability;
        Module[] modules;
    }

    /// @dev Grid geometry, derived from the denomination. Never hand-placed.
    struct Geometry {
        uint256 cols;
        uint256 rows;
        uint256 cell;
        uint256 x0;
        uint256 y0;
        uint256 halfCell;
    }

    function _geometry(uint256 di) private pure returns (Geometry memory g) {
        (g.cols, g.rows) = Denominations.gridAt(di);
        g.cell = FixedPoint.min(FIELD_W / g.cols, FIELD_H / g.rows);
        g.x0 = FIELD_CX - (g.cols * g.cell) / 2;
        g.y0 = FIELD_CY - (g.rows * g.cell) / 2;
        g.halfCell = g.cell / 2;
    }

    /// @dev Distinct rotations a kind takes: 1 (rotation-invariant), 2 (the diagonal line), or 4.
    function _rotCount(uint256 kind) private pure returns (uint256) {
        if (kind == KIND_CIRCLE || kind == KIND_SQUARE || kind == KIND_DIAMOND) return 1;
        if (kind == KIND_LINE) return 2;
        return 4;
    }

    /// @dev One cell. Draws in the order kind -> solid -> rotation, consuming `rotation` only
    ///      for kinds with more than one orientation. `nextBelow` consumes a single stream value
    ///      whatever the bound, so a two-way kind stays aligned with the four-way ones.
    function _module(
        Round03Rand.Stream memory rnd,
        uint256 i,
        Geometry memory g,
        uint256 target,
        uint256 weight,
        uint256 solidProbability
    ) private pure returns (Module memory m) {
        m.kind = rnd.nextBelow(KIND_COUNT);
        m.solid = rnd.nextBelowProbability(solidProbability);
        uint256 rc = _rotCount(m.kind);
        m.rot = rc > 1 ? rnd.nextBelow(rc) * 90 : 0;

        m.weight = weight;
        m.size = _solveSize(m.kind, m.solid, target, weight);

        m.cx = g.x0 + (i % g.cols) * g.cell + g.halfCell;
        m.cy = g.y0 + (i / g.cols) * g.cell + g.halfCell;
    }

    /// @dev Map a uniform draw onto this card's solid probability.
    ///
    ///      A single global solid rate makes every card the same mixture. Drawing the rate per
    ///      card instead gives the collection a shape: a small share come out entirely
    ///      outlined, a small share entirely solid, and the rest land in a band. Both extremes
    ///      are exact — a card that draws 0 contains no solid mark at all — which is why the
    ///      per-module test is `draw < p` rather than `draw > t`.
    ///
    ///        r <  PURE_OUTLINE_CHANCE     -> 0    every module outlined
    ///        r >= 1 - PURE_SOLID_CHANCE   -> 1    every module solid
    ///        otherwise                    -> remapped linearly onto the band
    function _drawSolidProbability(uint256 r) private pure returns (uint256) {
        if (r < PURE_OUTLINE_CHANCE) return 0;
        uint256 upper = FixedPoint.WAD - PURE_SOLID_CHANCE;
        if (r >= upper) return FixedPoint.WAD;

        uint256 span = upper - PURE_OUTLINE_CHANCE;
        uint256 t = ((r - PURE_OUTLINE_CHANCE) * FixedPoint.WAD) / span;
        return SOLID_BAND_MIN + t.mulWad(SOLID_BAND_MAX - SOLID_BAND_MIN);
    }

    /// @dev How this card came out of the fill draw. Solid and Outline are the rare extremes.
    function _fillClass(Card memory card) private pure returns (string memory) {
        if (card.solidProbability == 0) return "Outline";
        if (card.solidProbability == FixedPoint.WAD) return "Solid";
        return "Mixed";
    }

    /// @dev Solve the path footprint that paints to exactly `target` from the cell centre.
    ///
    ///      A solid mark paints to its own edge, so its footprint is simply `2 * target`. An
    ///      outlined mark is grown by its stroke, and by how much depends on the corners:
    ///
    ///        circle, square, half circle   the stroke straddles the edge, adding w/2 all
    ///                                      round -> size = 2 * target - w
    ///
    ///        triangle                      60 degree corners. A miter join at angle t extends
    ///                                      the corner by (w/2) / sin(t/2) along the bisector;
    ///                                      at 60 degrees that is a full w, not half of one.
    ///                                      Offsetting outward by w/2 grows the side by
    ///                                      sqrt(3) * w -> size = 2 * target - sqrt(3) * w
    ///
    ///      This is what makes containment exact rather than a headroom argument: the painted
    ///      extent is the controlled quantity, so no primitive can reach past its cell.
    ///      With w capped at 0.17 of the painted width the triangle case stays well positive:
    ///      2T - sqrt(3) * 0.34T = 1.41T.
    function _solveSize(uint256 kind, bool solid, uint256 target, uint256 weight)
        private
        pure
        returns (uint256)
    {
        uint256 full = 2 * target;
        // Open strokes are never filled; their footprint is always the outlined size. The arc's
        // endpoints reach w/2 past the footprint like a square; the diagonal line meets the axis
        // at 45 degrees, so its cap projects only (sqrt(2)/4)*w and it is grown to compensate.
        if (kind == KIND_ARC) return full - weight;
        if (kind == KIND_LINE) return full - (SQRT2 / 2).mulWad(weight);
        if (solid) return full;
        if (kind == KIND_TRIANGLE) return full - SQRT3.mulWad(weight);
        // The right triangle's two acute corners are 45 degrees, sharper than the equilateral's
        // 60, so a miter reaches (1 + sqrt(2))/2 * w along the axis. Inset by (1 + sqrt(2)) * w
        // so the outermost miter tip lands exactly on the target.
        if (kind == KIND_RTRIANGLE) return full - ONE_PLUS_SQRT2.mulWad(weight);
        // Every other primitive meets its corners at 90 degrees or not at all, so the stroke
        // adds exactly w/2 on each axis. A diamond's corners point along the axes, where a
        // 90 degree miter reaches (w/2)*sqrt(2) along the bisector — axis component w/2.
        return full - weight;
    }

    /// @notice Resolve a token into its full geometric description.
    /// @dev Draw order, consensus critical (SPEC.md D5):
    ///        1. fill     — always
    ///        2. wRatio   — always
    ///      then per cell, row-major:
    ///        3. kind     — always
    ///        3. solid probability — always
    ///      then per cell:
    ///        4. kind     — always
    ///        5. solid    — always
    ///        5. rotation — only when the kind takes more than one orientation
    ///      The conditional consumption is load-bearing. Drawing unconditionally would
    ///      desynchronise the stream and change every subsequent cell on the card.
    function compose(bytes32 seed, uint256 amountWei) public pure returns (Card memory card) {
        uint256 di = Denominations.requireIndexOf(amountWei);
        Geometry memory g = _geometry(di);
        Round03Rand.Stream memory rnd = Round03Rand.init(seed);

        card.denomIndex = di;
        card.cols = g.cols;
        card.rows = g.rows;
        card.cell = g.cell;
        card.fill = FILL;
        card.wRatio = WRATIO;
        card.target = g.halfCell.mulWad(FILL);
        card.weight = (2 * card.target).mulWad(card.wRatio);
        card.solidProbability = _drawSolidProbability(rnd.nextWad());

        uint256 n = g.cols * g.rows;
        card.modules = new Module[](n);
        for (uint256 i = 0; i < n; ++i) {
            card.modules[i] = _module(rnd, i, g, card.target, card.weight, card.solidProbability);
        }
    }

    /* ------------------------------------------------------------------ *
     *  SVG
     * ------------------------------------------------------------------ */

    function _style(bool solid, uint256 weight) private pure returns (bytes memory) {
        return solid
            ? bytes(' fill="#fff"/>')
            : abi.encodePacked(' fill="none" stroke="#fff" stroke-width="', weight.fmt(), '"/>');
    }

    function _transform(uint256 rot, uint256 cx, uint256 cy) private pure returns (bytes memory) {
        if (rot == 0) return "";
        return abi.encodePacked(
            ' transform="rotate(', FixedPoint.toString(rot), " ", cx.fmt(), " ", cy.fmt(), ')"'
        );
    }

    function _moduleSvg(Module memory m) private pure returns (bytes memory) {
        uint256 r = m.size / 2;

        if (m.kind == KIND_CIRCLE) {
            return abi.encodePacked(
                '<circle cx="', m.cx.fmt(), '" cy="', m.cy.fmt(), '" r="', r.fmt(), '"',
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_SQUARE) {
            return abi.encodePacked(
                '<rect x="', (m.cx - r).fmt(), '" y="', (m.cy - r).fmt(),
                '" width="', m.size.fmt(), '" height="', m.size.fmt(), '"',
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_TRIANGLE) {
            uint256 half = m.size.mulWad(TRI_HEIGHT) / 2;
            return abi.encodePacked(
                '<polygon points="',
                m.cx.fmt(), ",", (m.cy - half).fmt(), " ",
                (m.cx + r).fmt(), ",", (m.cy + half).fmt(), " ",
                (m.cx - r).fmt(), ",", (m.cy + half).fmt(),
                '"',
                _transform(m.rot, m.cx, m.cy),
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_QUARTER) {
            // A quarter disc whose right-angle corner sits at one corner of the footprint and
            // whose arc sweeps to the opposite two: a square with one corner rounded away.
            // The arc radius is the full footprint, not half of it.
            return abi.encodePacked(
                '<path d="M', (m.cx - r).fmt(), ",", (m.cy + r).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy + r).fmt(),
                " A", m.size.fmt(), ",", m.size.fmt(), " 0 0 0 ",
                (m.cx - r).fmt(), ",", (m.cy - r).fmt(), ' Z"',
                _transform(m.rot, m.cx, m.cy),
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_DIAMOND) {
            // The square on its diagonal, emitted as its four vertices so the geometry is
            // explicit and the miter maths stays in one place. Never rotated.
            return abi.encodePacked(
                '<polygon points="',
                m.cx.fmt(), ",", (m.cy - r).fmt(), " ",
                (m.cx + r).fmt(), ",", m.cy.fmt(), " ",
                m.cx.fmt(), ",", (m.cy + r).fmt(), " ",
                (m.cx - r).fmt(), ",", m.cy.fmt(),
                '"',
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_HALFSQUARE) {
            // Half the cell, split by a straight edge: a rectangle filling the upper half of the
            // footprint at rotation 0. The rectangular twin of the half circle.
            return abi.encodePacked(
                '<rect x="', (m.cx - r).fmt(), '" y="', (m.cy - r).fmt(),
                '" width="', m.size.fmt(), '" height="', r.fmt(), '"',
                _transform(m.rot, m.cx, m.cy),
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_RTRIANGLE) {
            // The square cut on its diagonal: right angle at the top-left footprint corner at
            // rotation 0, hypotenuse from top-right to bottom-left.
            return abi.encodePacked(
                '<polygon points="',
                (m.cx - r).fmt(), ",", (m.cy - r).fmt(), " ",
                (m.cx + r).fmt(), ",", (m.cy - r).fmt(), " ",
                (m.cx - r).fmt(), ",", (m.cy + r).fmt(),
                '"',
                _transform(m.rot, m.cx, m.cy),
                _style(m.solid, m.weight)
            );
        }

        if (m.kind == KIND_ARC) {
            // The quarter disc's curved edge alone: an open 90 degree arc, no radii, always
            // stroked. Radius is the full footprint, sweeping between two opposite corners.
            return abi.encodePacked(
                '<path d="M', (m.cx + r).fmt(), ",", (m.cy + r).fmt(),
                " A", m.size.fmt(), ",", m.size.fmt(), " 0 0 0 ",
                (m.cx - r).fmt(), ",", (m.cy - r).fmt(), '"',
                _transform(m.rot, m.cx, m.cy),
                _style(false, m.weight)
            );
        }

        if (m.kind == KIND_LINE) {
            // A straight diagonal across the cell, corner to corner, always stroked.
            return abi.encodePacked(
                '<path d="M', (m.cx - r).fmt(), ",", (m.cy - r).fmt(),
                " L", (m.cx + r).fmt(), ",", (m.cy + r).fmt(), '"',
                _transform(m.rot, m.cx, m.cy),
                _style(false, m.weight)
            );
        }

        // half circle: flat edge through the cell centre, filled half above at rotation 0
        return abi.encodePacked(
            '<path d="M', (m.cx - r).fmt(), ",", m.cy.fmt(),
            " A", r.fmt(), ",", r.fmt(), " 0 0 1 ", (m.cx + r).fmt(), ",", m.cy.fmt(), ' Z"',
            _transform(m.rot, m.cx, m.cy),
            _style(m.solid, m.weight)
        );
    }

    /// @inheritdoc IShapeRenderer
    /// @dev A Shape carries no type: black field, white marks, nothing else. The denomination
    ///      and the token number live in the metadata, not on the card face.
    function renderSVG(bytes32 seed, uint256 amountWei) public pure returns (string memory) {
        Card memory card = compose(seed, amountWei);

        bytes memory body;
        uint256 n = card.modules.length;
        for (uint256 i = 0; i < n; ++i) {
            body = abi.encodePacked(body, _moduleSvg(card.modules[i]));
        }

        return string(
            abi.encodePacked(
                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 350"'
                ' width="250" height="350" shape-rendering="geometricPrecision">'
                '<rect x="0" y="0" width="250" height="350" fill="#000"/>',
                body,
                "</svg>"
            )
        );
    }

    /* ------------------------------------------------------------------ *
     *  Module glyph sequence
     * ------------------------------------------------------------------ */

    /// @dev Glyphs from the Geometric Shapes block, matching the vocabulary of Round 04 of
    ///      the same design exploration. Derived from the composition, never re-rolled, so
    ///      the trait and the artwork always describe the same token (SPEC.md D10).
    function _glyph(Module memory m) private pure returns (string memory) {
        if (m.kind == KIND_CIRCLE) return m.solid ? unicode"●" : unicode"○";
        if (m.kind == KIND_SQUARE) return m.solid ? unicode"■" : unicode"□";
        if (m.kind == KIND_QUARTER) return m.solid ? unicode"◔" : unicode"◷";
        if (m.kind == KIND_DIAMOND) return m.solid ? unicode"◆" : unicode"◇";
        if (m.kind == KIND_TRIANGLE) {
            if (m.solid) {
                if (m.rot == 0) return unicode"▲";
                if (m.rot == 90) return unicode"▶";
                if (m.rot == 180) return unicode"▼";
                return unicode"◀";
            }
            if (m.rot == 0) return unicode"△";
            if (m.rot == 90) return unicode"▷";
            if (m.rot == 180) return unicode"▽";
            return unicode"◁";
        }
        if (m.kind == KIND_HALFSQUARE) {
            if (m.rot == 0) return unicode"⬒";
            if (m.rot == 90) return unicode"◨";
            if (m.rot == 180) return unicode"⬓";
            return unicode"◧";
        }
        if (m.kind == KIND_RTRIANGLE) {
            if (m.rot == 0) return unicode"◸";
            if (m.rot == 90) return unicode"◹";
            if (m.rot == 180) return unicode"◿";
            return unicode"◺";
        }
        if (m.kind == KIND_ARC) {
            if (m.rot == 0) return unicode"◜";
            if (m.rot == 90) return unicode"◝";
            if (m.rot == 180) return unicode"◞";
            return unicode"◟";
        }
        if (m.kind == KIND_LINE) {
            return m.rot == 0 ? unicode"╲" : unicode"╱";
        }
        if (m.rot == 0) return unicode"◓";
        if (m.rot == 90) return unicode"◑";
        if (m.rot == 180) return unicode"◒";
        return unicode"◐";
    }

    function _moduleSequence(Card memory card) private pure returns (bytes memory out) {
        uint256 n = card.modules.length;
        for (uint256 i = 0; i < n; ++i) {
            out = i == 0
                ? bytes(_glyph(card.modules[i]))
                : abi.encodePacked(out, " ", _glyph(card.modules[i]));
        }
    }

    /// @inheritdoc IShapeRenderer
    function moduleSequence(bytes32 seed, uint256 amountWei) external pure returns (string memory) {
        return string(_moduleSequence(compose(seed, amountWei)));
    }

    /* ------------------------------------------------------------------ *
     *  Metadata
     * ------------------------------------------------------------------ */

    function _hex32(bytes32 v) private pure returns (bytes memory out) {
        bytes memory alphabet = "0123456789abcdef";
        out = new bytes(66);
        out[0] = "0";
        out[1] = "x";
        for (uint256 i = 0; i < 32; ++i) {
            out[2 + i * 2] = alphabet[uint8(v[i]) >> 4];
            out[3 + i * 2] = alphabet[uint8(v[i]) & 0x0f];
        }
    }

    /// @inheritdoc IShapeRenderer
    function metadataJSON(bytes32 seed, uint256 amountWei, uint256 tokenId)
        public
        pure
        returns (string memory)
    {
        Card memory card = compose(seed, amountWei);
        string memory svg = renderSVG(seed, amountWei);

        return string(
            abi.encodePacked(
                '{"name":"Shape #',
                FixedPoint.toString(tokenId),
                '","description":"',
                DESCRIPTION,
                '","image":"data:image/svg+xml;base64,',
                Base64.encode(bytes(svg)),
                '","attributes":[{"trait_type":"ETH Value","value":"',
                Denominations.labelAt(card.denomIndex),
                ' ETH"},{"trait_type":"Grid","value":"',
                FixedPoint.toString(card.cols),
                "x",
                FixedPoint.toString(card.rows),
                '"},{"trait_type":"Fill","value":"',
                _fillClass(card),
                '"},{"trait_type":"Modules","value":"',
                _moduleSequence(card),
                '"},{"trait_type":"Module Count","value":',
                FixedPoint.toString(card.cols * card.rows),
                '},{"trait_type":"Seed","value":"',
                _hex32(seed),
                '"}]}'
            )
        );
    }

    /// @inheritdoc IShapeRenderer
    function tokenURI(bytes32 seed, uint256 amountWei, uint256 tokenId)
        external
        pure
        returns (string memory)
    {
        return string(
            abi.encodePacked(
                "data:application/json;base64,",
                Base64.encode(bytes(metadataJSON(seed, amountWei, tokenId)))
            )
        );
    }
}
